<?php
/*
 --------------------------------------------------------------------------
                            GAzie - Gestione Azienda
    Copyright (C) 2004-2015 - Antonio De Vincentiis Montesilvano (PE)
         (http://www.devincentiis.it)
           <http://gazie.sourceforge.net>
 --------------------------------------------------------------------------
    Questo programma e` free software;   e` lecito redistribuirlo  e/o
    modificarlo secondo i  termini della Licenza Pubblica Generica GNU
    come e` pubblicata dalla Free Software Foundation; o la versione 2
    della licenza o (a propria scelta) una versione successiva.

    Questo programma  e` distribuito nella speranza  che sia utile, ma
    SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
    NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
    veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

    Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
    Generica GNU insieme a   questo programma; in caso  contrario,  si
    scriva   alla   Free  Software Foundation,  Inc.,   59
    Temple Place, Suite 330, Boston, MA 02111-1307 USA Stati Uniti.
 --------------------------------------------------------------------------
*/

$strScript = array ("admin_client.php" =>
                   array(  'title'=>'Customers management',
                           'ins_this'=>'Insert new customer',
                           'upd_this'=>'Update customer',
                           'mesg'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer'
                                          ),
                           'errors'=>array('Must indicate the company name',
                                           'Must indicate the address',
                                           'Invalid postal code',
                                           'Must indicate the city',
                                           'Must indicate the province',
                                           'Must indicate the sex',
                                           'L\'IBAN is  incorrect',
                                           'The IBAN and the nation are different',
                                           'Tax Code incorrect for an individual',
                                           'VAT registration number is incorrect',
                                           'There is already a customer with the same VAT registration number',
                                           'Tax code is incorrect',
                                           'There is already a customer with the same Tax Code',
                                           'Tax code missing! Is automatically set with <br />the same value of the VAT registration number',
                                           'Is an individual, enter the Tax Code',
                                           'Is there a registry with the same VAT registration number',
                                           'Is there a registry with the same Tax code',
                                           'You must choose your payment method',
                                           'The customer code is already there, try the entry with the one proposed (plus 1)',
                                           'The date of birth is wrong',
                                           'Email address formally wrong'
                                          ),
                           'link_anagra'=>' Click below to enter the existing registry on the your chart of accounts',
                           'codice'=>"Code ",
                           'ragso1'=>"Company Name 1",
                           'ragso2'=>"Company Name 2",
                           'sedleg'=>"Registered Office",
                           'luonas'=>'Birthplace',
                           'datnas'=>'Date of birth',
                           'pronas'=>'Province of birth',
                           'counas'=>'Country of birth',
                           'legrap'=>"Legal representative ",
                           'sexper'=>"Sex/legal person",
                           'sexper_value'=>array(''=>'-','M'=>'Male','F'=>'Female','G'=>'Legal'),
                           'indspe'=>'Address',
                           'capspe'=>'Postal Code',
                           'citspe'=>'City - Province',
                           'country'=>'Nation',
                           'id_language'=>'Language',
                           'id_currency'=>'Currency',
                           'telefo'=>'Telephone',
                           'fax'=>'Fax',
                           'cell'=>'Cellphone',
                           'codfis'=>'Tax code',
                           'pariva'=>'VAT registration number',
                           'e_mail'=>'e mail',
                           'id_agente'=>'Sales Representative',
                           'codpag'=>'Payment method*',
                           'sconto'=>'% Discount applied',
                           'banapp'=>'Bank support',
                           'portos'=>'Rendered port',
                           'spediz'=>'Delivery',
                           'imball'=>'Package',
                           'listin'=>'Pricelist applied',
                           'id_des'=>'Destination &rArr; from registry',
                           'destin'=>'Destination &rArr; free description',
                           'iban'=>'IBAN',
                           'maxrat'=>'Maximum amount of bills',
                           'ragdoc'=>'Grouping documents',
                           'addbol'=>'Charge the stamp expenses',
                           'speban'=>'Charge the bank expenses',
                           'spefat'=>'Charge the cost of billing',
                           'stapre'=>'Print prices on shipping documents',
                           'op_type'=>'Operation type',
                           'op_type_value'=>array(1=>'Sale of goods',2=>'Selling services'),
                           'allegato'=>'Attached VAT - Customers report',
                           'yn_value'=>array('S'=>'Yes','N'=>'No'),
                           'aliiva'=>'VAT reduction',
                           'ritenuta'=>'% Withholding',
                           'status'=>'Visibility at the research',
                           'status_value'=>array(''=>'Yes','HIDDEN'=>'Hidden'),
                           'annota'=>'Note',
                           'fe_cod_univoco'=>'Unique Customer Code (electronic invoice)'
                         ),
                   "report_docven.php" =>
                   array('title'=>'Lista dei documenti di vendita',
                         'mail_alert0'=>'Invio documento con email',
                         'mail_alert1'=>'Hai scelto di inviare una e-mail all\'indirizzo: ',
                         'mail_alert2'=>'con allegato il seguente documento di vendita:'
                         ),
                    "admin_agenti.php" =>
                   array(  "Sales agents ",
                           "Sales agent",
                           "Number",
                           "Supplier",
                           "Telephon",
                           "Fax",
                           "% Commissions",
                           "Item Group",
                           "Item",
                           "Rate",
                           "Specified by ",
                           "Already inserted!",
                           "Lack of data necessary to add a line!",
                           "The rate of commission must be greater than 0.01!",
                           "You are trying to insert an agent without link to a supplier!",
                           "Is not inserted the agent number",
                           "You are trying to enter a supplier that is already an agent!",
                           "You are trying to insert an agent number that already exists!",
                           "You are deleting an agent!",
                           "List of Commissions",
                           'title'=>'Managing Salespeople',
                           'ins_this'=>'Insert an new sales agent'
                           ),
                    "select_provvigioni.php" =>
                   array(  "Selezione per Stampa lista Provvigioni",
                           "Agente di vendita",
                           "Tutti gli Agenti",
                           "Inserire min. 2 caratteri!",
                           "Non &egrave; stato trovato nulla!",
                           "Data periodo inizio",
                           "Data periodo fine"
                           ),
                    "admin_docven.php" =>
                   array(  array("DDT" => "Sales delivery note",
                                 "FAD" => "Invoiced delivery note",
                                 "FAI" => "Immediately invoice",
                                 "FAP" => "Bill",
                                 "FNC" => "Credit Note to customer",
                                 "FND" => "Debit Note to customer",
                                 "VCO" => "Ticket Sales",
                                 "VRI" => "Received"
                                 ),
                           'mesg'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer / supplier'
                                          ),
                           " body ",
                           " footer ",
                           " Pull up ",
                           " Section ",
                           " Address ",
                           " Date ",
                           " Price list ",
                           " Payment ",
                           " Bank ",
                           " Consignee ",
                           " Causal ",
                           " warehouse ",
                           " sales " ,
                           "Vector",
                           "Item",
                           "Quantity",
                           "Type",
                           "Revenue",
                           "V.A.T.",
                           "Code",
                           "Description",
                           "M.U.",
                           "Price",
                           "Reduction",
                           "Amount",
                           "Pack",
                           "Delivery",
                           "Transport",
                           "Rendered port",
                           "Beginning transport",
                           "hours",
                           "Taxable",
                           "Tax",
                           "Body amount",
                           "Weight",
                           "Total",
                           "Beginning transport date is not correct!",
                           "Beginning transport date previous to the emissino date!",
                           "There isn't any document row!",
                           "Stai tentando di modificare il DdT con una data antecedente a quella del DdT con numero precedente!",
                           "Stai tentando di modificare il DdT con una data successiva a quella del DdT con numero successivo!",
                           "Stai tentando di modificare il documento con una data antecedente a quello dello stesso tipo di documento con numero precedente!" ,
                           "Stai tentando di modificare il documento con una data successiva a quello dello stesso tipo di documento con numero successivo!" ,
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo DdT emesso!",
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo documento dello stesso tipo emesso!",
                           "La data di emissione non &egrave; corretta!",
                           "Non hai selezionato il cliente!",
                           "Non hai selezionato la modalit&agrave; di pagamento!",
                           "Un rigo &egrave; senza la descrizione!",
                           "Un rigo &egrave; senza l'unit&agrave; di misura!",
                           "Warehouse caus",
                           "Net weight",
                           "Gross weight",
                           "Units",
                           "Volume",
                           "Provvigioni",
                           "Vuoi modificare un D.d.T. gi&agrave; fatturato!",
                           "Questo documento &egrave; gi&agrave; stato contabilizzato!",
                           'speban'=>"Bank cost",
                           'speban_title'=>'Spese incasso non documentate/rate',
                           'traspo_title'=>'Spese trasporto non documentate',
                           'stamp'=>'Stamp tax',
                           'ritenuta'=>'Advance tax deduction ',
                           'netpay'=>'Net to pay ',
                           'id_agente'=>"Sales agent",
                           'in_artsea'=>'search for ',
                           'vat_constrain'=>'(constrain) VAT al ',
                           'taxstamp'=>'Taxstamp',
                           'virtual_taxstamp'=>'Mode',
                           'virtual_taxstamp_value'=>array(0=>'No',1=>'Material',2=>'Virtual'),
                           ),
                    "select_docforprint.php" =>
                   array(  array(1 => "D.d.T. di Vendita",2 => "Fattura Differita",3 => "Fattura Immediata Accompagnatoria",4 => "Fattura Immediata Semplice",5 => "Nota Credito a Cliente",6 => "Nota Debito a Cliente"),
                           " nella sezione ",
                           "Data",
                           "Protocollo",
                           "Numero",
                           " inizio",
                           " fine",
                           "Tipo ",
                           "Selezione Cliente ",
                           "inserire min. 2 caratteri!",
                           "Tutti i clienti!",
                           "Non &egrave; stato trovato nulla!",
                           "Il numero inizio dev'essere maggiore di zero !",
                           "Il numero fine dev'essere maggiore o uguale al numero inizio !",
                           "Il protocollo inizio dev'essere maggiore di zero !",
                           "Il protocollo fine dev'essere maggiore o uguale al protocollo inizio !",
                           "La data inizio non &egrave; corretta !",
                           "La data fine non &egrave; corretta !",
                           "La data fine dev'essere successiva a quella di inizio !",
                           "Non ci sono documenti stampabili negli intervalli selezionati !"
                           ),
                    "admin_broven.php" =>
                   array( array("VPR" => "Quotation to customer","VOR" => "Order from customer","VOW" => "Order from web site"),
                           'mesg'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer / supplier'
                                          ),
                           " corpo ",
                           " piede ",
                           " Tira su ",
                           " Sezione ",
                           " Indirizzo ",
                           " Data ",
                           " Listino ",
                           " Pagamento ",
                           " Banca ",
                           " Destinazione ",
                           " Causale ",
                           " magazzino ",
                           " vendita " ,
                           "Vettore",
                           "Articolo",
                           "Quantit&agrave;",
                           "Tipo",
                           "Ricavo",
                           "I.V.A.",
                           "Codice",
                           "Descrizione",
                           "U.M.",
                           "Prezzo",
                           "Sconto",
                           "Importo",
                           "Imballo",
                           "Spedizione",
                           "Trasporto",
                           "Porto",
                           "Inizio trasporto",
                           " ore ",
                           "Imponibile",
                           "Imposta",
                           "Body amount",
                           "Peso",
                           "Totale",
                           "La data di inizio trasporto non &egrave; corretta!",
                           "La data di inizio trasporto non pu&ograve; essere precedente alla data di emissione!",
                           "Non ci sono righi per poter emettere il documento!",
                           "Stai tentando di modificare il DdT con una data antecedente a quella del DdT con numero precedente!",
                           "Stai tentando di modificare il DdT con una data successiva a quella del DdT con numero successivo!",
                           "Stai tentando di modificare il documento con una data antecedente a quello dello stesso tipo di documento con numero precedente!" ,
                           "Stai tentando di modificare il documento con una data successiva a quello dello stesso tipo di documento con numero successivo!" ,
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo DdT emesso!",
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo documento dello stesso tipo emesso!",
                           "La data di emissione non &egrave; corretta!",
                           "Non hai selezionato il cliente!",
                           "Non hai selezionato la modalit&agrave; di pagamento!",
                           "Un rigo &egrave; senza la descrizione!",
                           "Un rigo &egrave; senza l'unit&agrave; di misura!",
                           "Causale mag.",
                           "Peso netto",
                           "Peso lordo",
                           "N.Colli",
                           "Volume",
                           "Provvigioni",
                           "Vuoi modificare un D.d.T. gi&agrave; fatturato!",
                           "Questo documento &egrave; gi&agrave; stato contabilizzato!",
                           'speban'=>"Spese incasso",
                           'speban_title'=>'Spese incasso non documentate/rate',
                           'traspo_title'=>'Spese trasporto non documentate',
                           'stamp'=>'Bolli',
                           'id_agente'=>"Agente di vendita",
                           'print_total'=>"Print total",
                           'print_total_value'=>array(0=>'No',1=>'Yes'),
                           'delivery_time'=>"Delivery_days",
                           'day_of_validity'=>"Days of validity",
                           'vat_constrain'=>'(contrain) VAT  ',
                           'taxstamp'=>'Taxstamp',
                           'virtual_taxstamp'=>'Mode',
                           'virtual_taxstamp_value'=>array(0=>'No',1=>'Material',2=>'Virtual'),

                           ),
                    "report_contract.php" =>
                    array( 'title'=>'Report of concluded contracts',
                           'vat_section'=>' of VAT section n.',
                           'link1'=>'Insert new contract',
                           'link2'=>'Create invoice/ticket from contracts',
                           'id'=>'ID',
                           'date'=>'Date',
                           'number'=>'Number',
                           'customer'=>'customer',
                           'current_fee'=>'Current fee'
                           ),
                    "admin_contract.php" =>
                    array( 'title'=>'Contract management',
                           'ins_this'=>'Insert new contract with ',
                           'upd_this'=>'Update contract concluded with ',
                           'errors'=>array('Data di stipula non corretta',
                                           'Data inizio periodo contrattuale non corretta',
                                           'Data ultimo adeguamento del canone non corretta',
                                           'Data di stipula successiva a quella di inizio',
                                           'Data di inizio successiva all\'ultimo adeguamento annuale',
                                           'Non &egrave; stato selezionato un cliente',
                                           'Non &egrave; stato selezionato un metodo di pagamento',
                                           'Almeno un rigo manca della descrizione',
                                           'Almeno un rigo manca della unit&agrave; di misura',
                                           'Il contratto non ha un testo',
                                           'Il canone corrente non pu&ograve; essere zero'
                                          ),
                           'mesg'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer / supplier'
                                          ),
                           'address'=>'Address',
                           'vat_section'=>'VAT section',
                           'doc_type'=> 'Receipt to be issued',
                           'doc_type_value'=>array('VRI'=>'Received','FAI'=>'Invoice'),
                           'doc_number'=>'Contract Number',
                           'conclusion_date'=>'Conclusion Date',
                           'start_date'=>'Start Date',
                           'months_duration'=>'Months duration',
                           'initial_fee'=>'Initial fee',
                           'periodic_reassessment'=>'Annual reassessment',
                           'bank'=>'Payment bank',
                           'payment_method'=>'Payment method',
                           'periodicity'=>'Periodicity',
                           'periodicity_value'=>array(1=>'monthly',2=>'bimonthly',3=>'quarterly',4=>'four-monthly',6=>'six-monthly',12=>'yearly'),
                           'tacit_renewal'=>'Tacit renewal',
                           'current_fee'=>'Current fee',
                           'cod_revenue'=>'Revenue account',
                           'vat_code'=>'VAT code',
                           'body_text'=>'Text of contract',
                           'last_reassessment'=>'Last reassessment',
                           'last_document_date'=>'Last document date',
                           'id_agente'=>'Agent',
                           'provvigione'=>'% commission',
                           'rows_title'=>'Other objections and / or descriptions',
                           'descri'=>'Objection description',
                           'unimis'=>'U.M.',
                           'quanti'=>'Quantity',
                           'price'=>'Price',
                           'discount'=>'Discount',
                           'append'=>'Appendix reminder for administrative use',
                           'customer'=>'Contractor customer'
                           ),
                    "delete_contract.php" =>
                    array( 'title'=>'Delete contract ',
                           'alert'=>'Are you sure you want to delete this contract?'
                           ),
                    "invoice_from_contract.php" =>
                    array( 'title'=>'Create invoice/received from the contracts',
                           'vat_section'=>' of the VAT section n.',
                           'on'=>' on ',
                           'period'=>'Period',
                           'period_value'=>array(1=>'mese di ',2=>'bimestre ',3=>'trimeste ',4=>'quadrimestre ',6=>'semestre ',12=>'annualità '),
                           'n_creation'=>'Number of doc',
                           'norows'=>'There are no contracts to be invoiced',
                           'expired'=>'Contract expired',
                           'err_date'=>'Date of last invoice<br />prior to the selected',
                           'ref'=>'From contract concluded in date '
                           ),
                    "admin_scontr.php" =>
                    array( 'title'=>'Menage tax receivable',
                           'ins_this'=>'issue a new tax receivable on : ',
                           'upd_this'=>'Update tax receivable n.',
                           'errors'=>array('Incorrect emissione date',
                                           'It was not a customer selected',
                                           'It was not a payment method selected',
                                           'In one row there isn\'t a description',
                                           'In one row there isn\'t a unit of measure',
                                           'The total of receivable can not be zero',
                                           'Payment is not expected to be collected automatically while an anonymous customer',
                                           'Incorrect fiscal code ',
                                           'YOU DO NOT HAVE DONE THE DAILY ACCOUNTING/CLOSURE OF CASH REGISTER',
                                           'The amount does not issue a sales document anonymously'
                                          ),
                           'customer'=>'customer',
                           'search_customer'=>array('Noto found!',
                                         'Insert min 2 characters!',
                                         'Change customer',
                                         'Coiche customer',
                                         ' F.C.:',
                                         'Anonymous'
                                          ),
                           'indspe'=>'Address',
                           'seziva'=>'VAT section',
                           'tipdoc'=> 'Document type',
                           'listin'=>'Listin n.',
                           'datemi'=>'Emission Date',
                           'caumag'=>'Warehouse causal',
                           'sconto'=>'Discount',
                           'address'=>'Address',
                           'pagame'=>'Payment',
                           'codric'=>'C/revenue',
                           'vat_constrain'=>'(constrain) VAT ',
                           'codvat'=>'%VAT',
                           'total'=>'Total',
                           'id_agente'=>'Agent',
                           'in_rows_title'=>'insert row',
                           'item'=>'Item',
                           'search'=>' search for ',
                           'in_artsea_value'=>array('C'=>'Item code', 'B'=>'Barcode','D'=>'Description'),
                           'tiprig'=> 'Type',
                           'tiprig_value'=>array(0=>'Normale',1=>'Forfait',2=>'Descrittivo'),
                           'body_title'=>'body',
                           'foot_title'=>'totals',
                           'upper_row'=>'Pusch up!',
                           'codart'=>'Codice',
                           'descri'=>'Description',
                           'unimis'=>'U.M.',
                           'quanti'=>'Quantity',
                           'prezzo'=>'Price',
                           'provvigione'=>'%Prov',
                           'amount'=>'Amount',
                           'sconto'=>'Discount',
                           'net'=>'Net Weight',
                           'units'=>'Pieces',
                           'volume'=>'Volume',
                           'taxable'=>'Taxable',
                           'tax'=>'V.A.T.',
                           'confirm'=>'Confirm sent data to ECR?'
                           
                           ),
                    "genera_effett.php" =>
                    array( 'title'=>'Generate the effects from tax documents',
                           'errors'=>array('There are no documents that can generate effects in the selected'
                                          ),
                           'preview'=>'Preview of effect creation',
                           'date_reg'=>'Date',
                           'protoc'=>'Protocol/Sect',
                           'doc_type'=>'Document type',
                           'doc_type_value'=>array('FAD'=>'DEFFERED INVOICE TO customER',
                                                   'FAI'=>'IMMEDIATELY INVOICE TO customER',
                                                   'FND'=>'DEBT NOTE TO customER'
                                                   ),
                           'type'=>'Type',
                           'type_value'=>array('B'=>' Bank Receipt',
                                               'T'=>' Draft',
                                               'V'=>' Payment against notice'
                                               ),
                           'customer'=>'customer',
                           'tot'=>'Total',
                           'total_value'=>array('B'=>'Total Receipts Banking',
                                                'T'=>'Total Drafts',
                                                'V'=>'Total Payment against notice'
                                               ),
                           'gen'=>'will generate',
                           'end'=>'ending '
                           ),
                    "distin_effett.php" =>
                    array( 'title'=>'Paper list of bank receipts and bill',
                           'errors'=>array('There aren\'t effects in the selected limit',
                                           'Incorrect Date',
                                           'The start date is later than the final',
                                           'The issue date is later than the initial'
                                          ),
                           'preview'=>'Preview of the paper list',
                           'header'=>array('Num'=>'','Type'=>'','Expiry date'=>'','Amount'=>'',
                                            'customer/V.R.' =>'','Invoice/Amount'=>'','Bank/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'List Date',
                           'bank'=>'Bank credit',
                           'date_ini'=>'Initial expiry date',
                           'date_fin'=>'Final expiry date',
                           'num_ini'=>'Initial number',
                           'num_fin'=>'Final number',
                           'period'=>'Select upcoming deadlines',
                           'period_value'=>'Upcoming deadlines',
                           'reprint'=>'Badged',
                           'reprint_value'=>array('S'=>'Yes','N'=>'No'),
                           'type'=>'Type of bill: ',
                           'type_value'=>array('B'=>'Bank receipt','T'=>'Bill','V'=>'MAV'),
                           'tot'=>'Total of list'
                           ),
                    "select_filerb.php" =>
                    array( 'title'=>'File RiBa creation (format CBI)',
                           'errors'=>array('There aren\'t effects in the selected limit',
                                           'Incorrect Date',
                                           'The start date is later than the final',
                                           'The issue date is later than the initial'
                                          ),
                           'preview'=>'Preview of file RiBa content ( CBI format)',
                           'header'=>array('Num'=>'','Type'=>'','Expiry date'=>'','Amount'=>'',
                                            'customer/V.R.' =>'','Invoice/Amount'=>'','Bank/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'List Date',
                           'bank'=>'Bank credit',
                           'date_ini'=>'Initial expiry date',
                           'date_fin'=>'Final expiry date',
                           'num_ini'=>'Initial number',
                           'num_fin'=>'Final number',
                           'period'=>'Select upcoming deadlines',
                           'period_value'=>'Upcoming deadlines',
                           'reprint'=>'Badged',
                           'reprint_value'=>array('S'=>'Yes','N'=>'No'),
                           'tot'=>'Total of file content',
                           'eof'=>'Record with characters at the end of line',
                           'eof_title'=>'Record with characters at the end of line chr 13 e 10'
                           ),
                    "select_filemav.php" =>
                    array( 'title'=>'File MAV creation (format CBI)',
                           'errors'=>array('There aren\'t effects in the selected limit',
                                           'Incorrect Date',
                                           'The start date is later than the final',
                                           'The issue date is later than the initial'
                                          ),
                           'preview'=>'Preview of file MAV content ( CBI format)',
                           'header'=>array('Num'=>'','Type'=>'','Expiry date'=>'','Amount'=>'',
                                            'customer/V.R.' =>'','Invoice/Amount'=>'','Bank/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'List Date',
                           'bank'=>'Bank credit',
                           'date_ini'=>'Initial expiry date',
                           'date_fin'=>'Final expiry date',
                           'num_ini'=>'Initial number',
                           'num_fin'=>'Final number',
                           'period'=>'Select upcoming deadlines',
                           'period_value'=>'Upcoming deadlines',
                           'reprint'=>'Badged',
                           'reprint_value'=>array('S'=>'Yes','N'=>'No'),
                           'tot'=>'Total of file content'
                           ),
                    "error_msg.php" =>
                    array( 'admin_scontr'=>array(0=>'WARNING!<br />She is not entitled to send data on the cash register (ECR), contact your administrator to change settings on the table gaz_cash_register.')
                          ),
                    "report_scontr.php" =>
                    array( 'title'=>'Report of tax receivable',
                           'seziva'=>' of the VAT section n.',
                           'link1'=>'Issue a new tax receivable',
                           'link2'=>'Run the daily closure of the cash register',
                           'id'=>'ID',
                           'date'=>'Date',
                           'number'=>'Number',
                           'invoice'=>'Attached invoices',
                           'status'=>'Status',
                           'status_value'=>array(0=>'ISSUED',1=>'REGISTERED'),
                           'send'=>'Retransmit to ECR',
                           'amount'=>'Amount'
                           ),
                    "report_broven.php" =>
                    array( 'title'=>'Quotes and orders',
                         'mail_alert0'=>'Invio documento con email',
                         'mail_alert1'=>'Hai scelto di inviare una e-mail all\'indirizzo: ',
                         'mail_alert2'=>'con allegato il seguente documento:',
                           'title_value'=>array('VPR'=>'Quotations to customers',
                                          'VOR'=>'Customer orders',
                                          'VOW'=>'Orders from the web'),
                           'link_title' =>array('VPR'=>'New Quotations to customer',
                                          'VOR'=>'New orders from customers',
                                          'VOW'=>'New orders from the web'),
                           'link_value' =>array('VPR'=>'admin_broven.php?Insert&tipdoc=VPR',
                                          'VOR'=>'admin_broven.php?Insert&tipdoc=VOR',
                                          'VOW'=>'import_gaziecart.php'),
                           'issue_ord'=>'Process orders',
                           'id'=>'ID',
                           'type'=>'Type',
                           'type_value' =>array('VPR'=>'Quotation',
                                          'VOR'=>'Order',
                                          'VOW'=>'Web order'),
                           'date'=>'Date',
                           'number'=>'Number',
                           'status'=>'State',
                           'issue'=>'Issue',
                           'status_value'=>array(0=>'',1=>'ISSUED')
                           ),
                    "resend_to_ecr.php" =>
                    array( 'title'=>'Retransmission data to cash resgister',
                           'head'=>'Reissue the receipt n.',
                           'on'=>' on: ',
                           'total'=>'TOTAL Amount',
                           'message'=>" WARNING!!! <br />You are trying to reissue a tax receipt issued, this is not normal.<br />Only when you have experienced problems that have prevented the transmission of data to the recorder in the process of issuing a new ticket that is right.<br />Before proceeding we recommend to do it manually on the recorder to make sure that it is not left in a state of waiting and then failed to complete the release",
                           'submit'=>'Forward anyway'
                           ),
                    "close_ecr.php" =>
                    array( 'title1'=>'Perform the closure of the cash register ',
                           'title2'=>' and trasfer the receipts issued to the book.',
                           'message'=>"WARNING!!! <br />No tickets are issued and not closed/booked on this cash register",
                           'date'=>'Date',
                           'num'=>'Number',
                           'sez'=>'VAT sect.',
                           'customer'=>'customer',
                           'anony'=>'Anonymous',
                           'importo'=>'Amount'
                           ),
                    "accounting_documents.php" =>
                    array( 'title'=>'Create movements accounting from taxable documents',
                           'errors'=>array('Incorrect date',
                                           'There are no documents to be written in the selected'
                                          ),
                           'vat_section'=>' of VAT section n.',
                           'date'=>'Until :',
                           'type'=>'VAT register ',
                           'type_value'=>array('F'=>'of Sales Invoices','V'=>'of Charges'),
                           'proini'=>'Initial protocol',
                           'profin'=>'Final protocol',
                           'preview'=>'Accounting preview',
                           'date_reg'=>'Date',
                           'protoc'=>'Protocol',
                           'doc_type'=>'Type',
                           'doc_type_value'=>array('FAD'=>'DEFERRED INVOICE TO THE customER',
                                                   'FAI'=>'IMMEDIATE INVOICE TO THE customER',
                                                   'FNC'=>'CREDIT NOTE TO THE customER',
                                                   'FND'=>'DEBT NOTE TO THE customER',
                                                   'VCO'=>'FEES',
                                                   'VRI'=>'RECEIVED',
                                                   'AFA'=>'PURCHASE INVOICE',
                                                   'AFC'=>'CREDIT NOTE FROM PURCHASE',
                                                   'AFD'=>'DEBT NOTE FROM PURCHASE'
                                                   ),
                           'customer'=>'customer/Supplier',
                           'taxable'=>'Taxable',
                           'vat'=>'VAT',
                           'stamp'=>'Stamps on bills',
                           'tot'=>'Total'
                           ),
                    "import_gaziecart.php" =>
                    array( 'title'=>'Import order from Joomla-GAzieCart web site',
                           'errors'=>array('There are no orders to be imported from the mailbox'
                                          ),
                           'email'=>'Address used to receive orders: ',
                           'pass'=>'Password used to access: ',
                           'server'=>'Server Address: ',
                           'name'=>'WEB Order',
                           'amount'=>'Taxable Total',
                           'tot'=>'TOTAL ',
                           'tax'=>'V.A.T.',
                           'des1'=>' on the website: ',
                           'mesg'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer / supplier'
                                          ),
                           'errors'=>array('Select the customer!',
                                           'Select the type of payment',
                                           'Enable the php_imap extension on php.ini to import orders'
                                          ),
                           ),
                    "select_effett.php" =>
                    array( 0=>'Print bills',
                           'title'=>'Select for view and/or print Bank receipts and Bills',
                           'ins_this'=>'Issue bill of exchange to:',
                           'upd_this'=>'Update bill of exchange to: ',
                           'del_this'=>'Delete bill of exchange',
                           'sourcedoc'=>'Document source of bill',
                           'source'=>'Source',
                           'link_1'=>'Create bills from Invoice',
                           'link_2'=>'Issue new bill of exchange',
                           'link_3'=>'Accounting bills',
                           'link_4'=>'Print bills of exchange',
                           'link_5'=>'List for bank',
                           'link_6'=>'Create file Ri.Ba.',
                           'link_7'=>'Create file MAV',
                           'report'=>'Bills of exchange list',
                           'mesg'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer'
                                          ),
                           'errors'=>array('Incorrect date!',
                                           'The start date is later than the final',
                                           'Bill start number is greater than the final number!',
                                           'Invoice date is later than issue date!',
                                           'Issue date is later than expiry date!',
                                           'Invalid bill number ',
                                           'Select customer',
                                           'Invalid amount',
                                           'Select the bank support',
                                           'Select payment method'
                                          ),
                           'progre'=>'Number',
                           'type'=>'Type',
                           'type_pay'=>array('B'=>'Bank receipt','T'=>'Promissory','V'=>'MAV'),
                           'clfoco'=>'Customer',
                           'date_emi'=>'Date of Issue',
                           'numfat'=>'Number of invoice',
                           'vat_section'=>'VAT section',
                           'date_doc'=>'Invoice date',
                           'totfat'=>'Invoice amount',
                           'salacc'=>'Deposit / Balance',
                           'salacc_value'=>array('C'=>'Deposit','S'=>'Balance'),
                           'impeff'=>'Bill amount',
                           'status'=>'State',
                           'date_exp'=>'Expiry date',
                           'account_id'=>'Account record number',
                           'pagame'=>'Payment method',
                           'banapp'=>'Bank support',
                           'banacc'=>'Bank credit',
                           'num_ini'=>'Initial bill number ',
                           'date_ini'=>'Initial expiry date ',
                           'num_fin'=>'Final bill number ',
                           'date_fin'=>'Final expiry date ',
                           'type_value'=>array('B'=>'Bank receipts','T'=>'Drafts-bills','V'=>'MAV'),
                           'header'=>array('Num'=>'','Expiry date'=>'','Amount'=>'',
                                            'Customer' =>'','Invoice'=>'','Bank'=>''
                                           )
                           ),
                    "select_partner_status.php" =>
                    array( 'title'=>'Selezione per la visualizzazzione e/o la stampa dello scadenzario dei clienti',
                           'print_title'=>'SUPPLIERS DATETABLE ',
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'err'=>'Ci sono degli errori che impediscono la stampa'
                                          ),
                           'date_ini'=>'Data di riferimento ',
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni di esposizione' =>'','Stato'=>''
                                           ),
                            'status_value'=>array(0=>'OPEN',1=>'CLOSE',2=>'EXPOSED',3=>'EXPIRED',9=>'ADVANCED')
                           ),
                    "customer_payment.php" =>
                    array( 'title'=>'Riscossione credito da cliente (chiusura partita/e)',
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'err'=>'Ci sono degli errori che impediscono la stampa'
                                          ),
                           'partner'=>'Cliente ',
                           'date_ini'=>'Data di registrazione',
                           'target_account'=>"Conto per l'incasso: ",
                           'partner'=>'Cliente: ',
                           'print_ticket'=>"Stampa ricevuta: ",
                           'accbal'=>'Saldo risultante dai movimenti contabili: ',
                           'paymovbal'=>'Saldo risultante dalle partite aperte: ',
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>''
                                           ),
                           'status_value'=>array(0=>'APERTA',1=>'CHIUSA',2=>'ESPOSTA',3=>'SCADUTA',9=>'ANTICIPO'),
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>'', 'Riscuoti'=>''
                                           ),
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente',
                                         'Il saldo contabile è diverso da quello dello scadenzario,<br> se vuoi registrare la riscossione di un documento presente solo in contabilità fallo da qui:',
                                         'Nessun importo è stato riscosso!',
					 "Non è stato selezionato il conto per l'incasso",
                                         'Stai tentando di inserire il pagamento di un cliente senza movimenti'
                                          ),
                           ),
                    "report_schedule.php" =>
                    array( 'title'=>'Lista dei movimenti delle partite',
                           'header'=>array( 'ID'=>'id',
                                            'Identificativo partita' => "id_tesdoc_ref",
                                            'Movimento contabile apertura (documento)' => "id_rigmoc_doc",
                                            'Movimento contabile chiusura (pagamento)' => "id_rigmoc_pay",
                                            'Importo' => "amount",
                                            'Scadenza' => "expiry"
                                            ),
                           ),
                    "select_schedule.php" =>
                    array( 'title'=>'Selezione per la visualizzazzione e/o la stampa delle partite aperte',
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente/fornitore'
                                          ),
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'Non sono stati trovati movimenti!'
                                          ),
                           'account'=>'Cliente ',
                           'orderby'=>'Ordina per: ',
                           'orderby_value'=>array(0=>'Scadenza crescente',1=>'Scadenza decrescente',
                                                  2=>'Cliente crescente',3=>'Cliente decrescente'
                                           ),
                           'header'=>array('Cliente'=>'','ID Partita'=>'','Status'=>'','Mov.Cont.'=>'','Descrizione'=>'',
                                            'N.Doc.'=>'','Data Doc.' =>'','Data Reg.' =>'','Dare'=>'','Avere'=>'',
                                            'Scadenza'=>''
                                           ),
                           'status_value'=>array(0=>'CLOSE',1=>'OPEN'),
                           ),
                    "delete_schedule.php" =>
                    array( 'title'=>'Cancellazione movimenti chiusi dello scadenziario',
                           'ragsoc'=>'Cliente',
                           'id_tesdoc_ref'=>'Identificativo partita',
                           'descri'=> 'Descrizione'
                           ),
                    "select_evaord.php" =>
                    array( 'title'=>'Order picking of customer',
                           'errors'=>array('Non &egrave; stato selezionato un cliente',
                                           'Non ci sono righi',
                                           'Non ci sono righi inevasi per generare il documento selezionato',
                                           'Select payment method',
                                           'Incorrect date of issue',
                                           'Incorrect start date of transport',
                                           'Start date of transport prior to the issue date',
                                           'YOU HAVE NOT DONE THE CLOSING DAY OF THE CASH REGISTER TO DO BEFORE YOU GIVE A NEW ONE!'
                                          ),
                           'customer'=>'Customer',
                           'search_customer'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer',
                                         'Choice customer',
                                         ' F.C.:',
                                         'Anonymous'
                                          ),
                           'indspe'=>'Address',
                           'seziva'=>'VAT Section',
                           'destin'=>'Destination',
                           'banapp'=>'Bank',
                           'listin'=>'Price list n.',
                           'datemi'=>'Date ',
                           'initra'=>'Start date of transport ',
                           'traspo'=>'Transport ',
                           'spediz'=>'Delivery ',
                           'portos'=>'Rendered port ',
                           'imball'=>'Pack ',
                           'vettor'=>'Shippers ',
                           'sconto'=>'Discount',
                           'pagame'=>'Payment',
                           'preview_title'=>'BACKLOG:',
                           'from'=>'from Order n.',
                           'del'=>' of ',
                           'upd_ord'=>' Updtae order',
                           'id_agente'=>'Agent ',
                           'codart'=>'Code',
                           'descri'=>'Description',
                           'unimis'=>'M.U.',
                           'quanti'=>'Quantity',
                           'prezzo'=>'Price',
                           'provvigione'=>'%Ag.Com',
                           'amount'=>'Amount',
                           'taxable'=>'Taxable',
                           'issue_fat'=>'Issue with invoice',
                           'issue_ddt'=>'Issue with delivery note',
                           'issue_cor'=>'Issue with ticket',
                           'checkbox'=>'This checkbox must be selected to process the row',
                           'alert1'=>'&sup1; Section IVA choice is not one normally used for the issuance of immediately invoice',
                           'alert2'=>'&sup1; The selected section IVA may not coincide with what will be used for the immediate issuance of the invoice for your choice will be equal to the last emitted.'
                           ),
                    "print_customer_payment_receipt.php" =>
                    array( 'title'=>'RISCOSSIONE CREDITO DA ',
                           'id_tesdoc_ref'=>'ID Partita',
                           'descri'=>'Descrizione',
                           'numfat'=>'Numero fattura',
                           'datfat'=>'Data fattura',
                           'amount'=>'Importo riscosso',
                           'tot'=>'TOTALE DELLA RISCOSSIONE',
                           ),
                   "report_fae_sdi.php" =>
                   array(  'title'=>'TRAFFICO DATI FATTURAZIONE ELETTRONICA',
                           'table'=>'Tabella su cui stai lavorando: ',
                           'id'=>'ID',
                           'filename_ori'=>'Nome file primo invio',
                           'numfat'=>'N.<br>fattura',
                           'codice'=>'Cod. cliente',
                           'ragso1'=>'Amministrazione',
                           'exec_date'=>'Data di esecuzione ',
                           'received_date'=>'Data ricezione ',
                           'delivery_date'=>'Data consegna ',
                           'filename_son'=>'Nome file padre',
                           'id_SDI'=>'ID SDI',
                           'filename_ret'=>'Nome file di ritorno',
                           'mail_id'=>'UID della mail',
                           'flux_status'=>'Stato',
                           'flux_status_value'=>array(''=>'Generato',
						                              '#'=>'Non ancora inviata',
                                                      '@'=>'Inviata',
                                                      'NS'=>'Notifica scarto',
                                                      'MC'=>'Mancata Consegna',
                                                      'RC'=>'Ricevuta consegna',
                                                      'NE'=>'Notifica esito',
                                                      'DT'=>'Decorrenza termini'),
                           'progr_ret'=>'Progr.',
                           'flux_descri'=>'Descrizione'
                         )                           
                   );
?>