<?php
/*
 --------------------------------------------------------------------------
                            GAzie - Gestione Azienda
    Copyright (C) 2004-2015 - Antonio De Vincentiis Montesilvano (PE)
         (http://www.devincentiis.it)
           <http://gazie.sourceforge.net>
 --------------------------------------------------------------------------
    Questo programma e` free software;   e` lecito redistribuirlo  e/o
    modificarlo secondo i  termini della Licenza Pubblica Generica GNU
    come e` pubblicata dalla Free Software Foundation; o la versione 2
    della licenza o (a propria scelta) una versione successiva.

    Questo programma  e` distribuito nella speranza  che sia utile, ma
    SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
    NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
    veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

    Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
    Generica GNU insieme a   questo programma; in caso  contrario,  si
    scriva   alla   Free  Software Foundation,  Inc.,   59
    Temple Place, Suite 330, Boston, MA 02111-1307 USA Stati Uniti.
 --------------------------------------------------------------------------
*/

/*
 -- TRANSLATED BY : Dante Becerra Lagos (softenglish@gmail.com)
*/

$strScript = array ("admin_client.php" =>
                   array(  'title'=>'Administarcion de clientes',
                           'ins_this'=>'Insertar nuevo cliente',
                           'upd_this'=>'Actualizar cliente',
                           'mesg'=>array('La busqueda no dio resultados!',
                                         'Inserte al menos 2 caracteres!',
                                         'Cambiando cliente'
                                          ),
                           'errors'=>array('Usted debe indicar la Razon Social',
                                           'Usted debe indicar la direccion',
                                           'Usted debe indicar la CAP',
                                           'Usted debe indicar la ciudad',
                                           'Usted debe indicar la region',
                                           'Usted debe indicar el genero',
                                           'IBAN no es correcto',
                                           'IBAN y el pais son difrentes',
                                           'El codigo fiscal es obligatorio para una persona natural',
                                           'El IVA esta formalmente incorrecto!',
                                           'Existe ya un cliente con el mismo IVA',
                                           'El codigo fiscal esta formalmente incorrecto',
                                           'Existe ya un cliente con el mismo Codigo de Fiscal',
                                           'C.F. faltante! &iexcl;En autom&aacute;tico ha sido < br / > programado con el mismo valor del IVA!',
                                           'Es una persona natural, introduzca el c&oacute;digo fiscal',
                                           'Existe un registro con el mismo IVA',
                                           'Existe un registro con el mismo c&oacute;digo fiscal',
                                           'Usted debe elegir el metodo de pago',
                                           'El c&oacute;digo de cliente ya est&aacute; ah&iacute;, intentar la entrada con la que se propone (m&aacute;s 1)',
                                           'The date of birth is wrong',
                                           'Email formalmente mal la dirección'
                                          ),
                           'link_anagra'=>' Haga clic a continuaci&oacute;n para introducir sus datos personales en la tabla existente de cuentas',
                           'codice'=>"Codigo ",
                           'ragso1'=>"Nombre de la empresa 1",
                           'ragso2'=>"Nombre de la empresa 2",
                           'sedleg'=>"Domicilio Legal",
                           'luonas'=>'Birthplace',
                           'datnas'=>'Date of birth',
                           'pronas'=>'Province of birth',
                           'counas'=>'Country of birth',
                           'legrap'=>"Representante Legal ",
                           'sexper'=>"Genero/persona juridica ",
                           'sexper_value'=>array(''=>'-','M'=>'Masculino','F'=>'Femenino','G'=>'Juridica'),
                           'indspe'=>'Direccion',
                           'capspe'=>'Codigo Postal',
                           'citspe'=>'Ciudad - Region',
                           'country'=>'Pais',
                           'id_language'=>'Lengua',
                           'id_currency'=>'Moneda',
                           'telefo'=>'Telefono',
                           'fax'=>'Fax',
                           'cell'=>'Celular',
                           'codfis'=>'Codigo Fiscal',
                           'pariva'=>'I.V.A.',
                           'e_mail'=>'e mail',
                           'id_agente'=>'Agente',
                           'codpag'=>'Metodo de pago *',
                           'sconto'=>'% Descuento a plicar',
                           'banapp'=>'Banco de apoyo',
                           'portos'=>'Puerto - Rendimiento',
                           'spediz'=>'Embarque',
                           'imball'=>'Imballo',
                           'listin'=>'Lista de precios aplicados',
                           'id_des'=>'Destino del registro',
                           'destin'=>'Descripci&oacute;n del destino libre',
                           'iban'=>'IBAN',
                           'maxrat'=>'El importe m&aacute;ximo de la tasa',
                           'ragdoc'=>'Agrupaci&oacute;n de los documentos',
                           'addbol'=>'Pozo costo de debito',
                           'speban'=>'Costos bancarias de débito ',
                           'spefat'=>'Costes de facturaci&oacute;n de débito',
                           'stapre'=>'Los precios de impresion sobre el DDT ',
                           'op_type'=>'Tipos de operaciones',
                           'op_type_value'=>array(1=>'Venta de bienes',2=>'Venta de servicios'),
                           'allegato'=>'Anexo IVA - Clientes',
                           'yn_value'=>array('S'=>'Si','N'=>'No'),
                           'aliiva'=>'Reduccion de I.V.A.',
                           'ritenuta'=>'% Retenci&oacute;n',
                           'status'=>'Visibilidad de Investigacion',
                           'status_value'=>array(''=>'Activa','HIDDEN'=>'Desabilitada'),
                           'annota'=>'Anotaciones',
                           'fe_cod_univoco'=>'Código de cliente único (factura electrónica)'
                         ),
                   "report_docven.php" =>
                   array('title'=>'Lista dei documenti di vendita',
                         'mail_alert0'=>'Invio documento con email',
                         'mail_alert1'=>'Hai scelto di inviare una e-mail all\'indirizzo: ',
                         'mail_alert2'=>'con allegato il seguente documento di vendita:'
                         ),
                    "admin_agenti.php" =>
                   array(  "Agentes de venta ",
                           "Agentes de venta",
                           "Numero",
                           "Proveedor",
                           "Telefono",
                           "Fax",
                           "% Comisiones",
                           "Categoria Mercaderia",
                           "Articulo",
                           "Porcentaje",
                           "Especificos para ",
                           "ya se ha insertado!",
                           "Falta de datos necesarios para a&ntilde;adir una l&iacute;nea!",
                           "El porcentaje de la comisi&oacute;n debe ser superior a 0,01!",
                           "Usted est&aacute; tratando de insertar un agente sin conectarse a un proveedor!",
                           "No se incluy&oacute; el n&uacute;mero de agente",
                           "Estas intentando ingresar en un proveedor que ya es un agente!",
                           "Usted est&aacute; tratando de insertar un n&uacute;mero de agente que ya existe!",
                           "Esta elimimando un agente!",
                           "Lista de Comisiones ",
                           'title'=>'Administarcion de agente de venta',
                           'ins_this'=>'Insertar nuevo agente de venta'
                           ),
                    "select_provvigioni.php" =>
                   array(  "Seleccionar para imprimir la lista de las Comisiones ",
                           "Agente de venta",
                           "Todos los agentes ",
                           "Inserte min. 2 caracteres!",
                           "No se ha encontrado nada !",
                           "Fecha de Periodo inicio ",
                           "Fecha de Periodo final"
                           ),
                    "admin_docven.php" =>
                   array(  array("DDT" => "Nota de entrega de Ventas",
                                 "FAD" => "Nota de entrega faturada",
                                 "FAI" => "Factura Inmediata invoice",
                                 "FAP" => "Cuenta",
                                 "FNC" => "Nota de credito al cliente",
                                 "FND" => "Nota de debito al cliente",
                                 "VCO" => "Boleta de venta",
                                 "VRI" => "Recibido"
                                 ),
                           'mesg'=>array('La busqueda no dio resultados!',
                                         'Inserte al menos 2 caracteres!',
                                         'Cambiando cliente / proveedor'
                                          ),
                           " cuerpo ",
                           " pie de pagina ",
                           " Subir ",
                           " Seccion ",
                           " Direccion ",
                           " Fecha ",
                           " Lista de precios ",
                           " Pago ",
                           " Banco ",
                           " Consignatario ",
                           " Causal ",
                           " Bodega ",
                           " Ventas " ,
                           "Vector",
                           "Item",
                           "Cantidad",
                           "Tipo",
                           "Ingreso",
                           "I.V.A.",
                           "Codigo",
                           "Descripcion",
                           "M.U.",
                           "Precio",
                           "Reduccion",
                           "Cantidad",
                           "Empaque",
                           "Entrega",
                           "Transporte",
                           "Puerto ",
                           "Transporte de inicio",
                           "horass",
                           "Tributable",
                           "Impuesto",
                           "Cantidad Cuerpo",
                           "Peso",
                           "Total",
                           "Fecha de comienzo del transporte no es correcta!",
                           "Fecha de comienzo de transporte anteriores a la fecha de emision!",
                           "No hay ninguna fila  de documento !",
                           "tratas de cambiar el DDT, con una fecha anterior a la edici&oacute;n anterior con DDT!",
                           "tratas de cambiar el DDT con una fecha posterior a la del DDT con la pr&oacute;xima edici&oacute;n!",
                           "Est&aacute;s intentando editar el documento con una fecha anterior a el mismo documento con el n&uacute;mero anterior!" ,
                           "Est&aacute;s intentando editar el documento con fecha posterior a la del mismo documento con la pr&oacute;xima edici&oacute;n!" ,
                           "La fecha de emisi&oacute;n no puede ser anterior a la &uacute;ltima DDT emitida!",
                           "La fecha de emisi&oacute;n no puede ser anterior al &uacute;ltimo documento de la misma naturaleza emitido!",
                           "La fecha de emisi&oacute;n no es correcta!",
                           "Usted no ha seleccionado el cliente!",
                           "Non hai selezionato la modalit&agrave; di pagamento!",
                           "Una fila no tiene ninguna descripci&oacute;n!",
                           "Una l&iacute;nea es sin la unidad de medida!",
                           "Causal de Bodega",
                           "Peso Neto",
                           "Peso Bruto",
                           "Unidades",
                           "Volumen",
                           "Comisiones",
                           "Quieres modificar un D.d.T. ya facturado!",
                           "Este documento ya esta contabilizado",
                           'speban'=>"Gastos de recaudaci&oacute;n",
                           'speban_title'=>'Gastos de recaudaci&oacute;n no documentados/prorratas',
                           'traspo_title'=>'Gastos de transporte no documentados',
                           'stamp'=>'Sellos',
                           'ritenuta'=>'Deducci&oacute;n de impuestos por adelantado ',
                           'netpay'=>'Neto a pagar ',
                           'id_agente'=>"Agente de venta",
                           'in_artsea'=>'B&uacute;squeda por ',
                           'vat_constrain'=>'(forza) IVA al ',
                           'taxstamp'=>'Taxstamp',
                           'virtual_taxstamp'=>'Mode',
                           'virtual_taxstamp_value'=>array(0=>'No',1=>'Material',2=>'Virtual')
                           ),
                    "select_docforprint.php" =>
                   array(  array(1 => "D.d.T. de venta",2 => "Factura diferida",3 => "Factura inmediata que acompa&ntilde;a",4 => "Factura inmediata simple",5 => "Nota Credito a Cliente",6 => "Nota Debito a Cliente"),
                           " en la secci&oacute;n ",
                           "Fecha",
                           "Protocollo",
                           "Numero",
                           " inicio",
                           " termino",
                           "Tipo ",
                           "Seleccione Cliente ",
                           "inserte min. 2 caratteri!",
                           "Todos los clientes!",
                           "No se ha encontrado nada!",
                           "El n&uacute;mero inicio debe ser mayor que cero!",
                           "El n&uacute;mero de termino debe ser mayor o igual al n&uacute;mero inicio!",
                           "El protocolo debe ser mayor que cero!",
                           "El protocolo de termino debe ser mayor o igual que el protocolo de inicio !",
                           "La fecha inicio no es correcta!",
                           "La fecha termino no es correcta!",
                           "La fecha de finalizaci&oacute;n debe ser posterior al inicio !",
                           "Hay documentos imprimibles en los intervalos seleccionados !"
                           ),
                    "admin_broven.php" =>
                   array( array("VPR" => "Presupuestos para clientes","VOR" => "Pedidos de los clientes","VOW" => "Pedidos de los sitio web"),
                           'mesg'=>array('La busqueda no dio resultados!',
                                         'Inserte al menos 2 caracteres!',
                                         'Cambiando cliente / proveedor'
                                          ),
                           " cuerpo ",
                           " pie de pagina ",
                           " Tira sobre ",
                           " Secci&oacute;n ",
                           " Dirrecion ",
                           " Fecha ",
                           " Lista ",
                           " Pago ",
                           " Banco ",
                           " Destino ",
                           " Causal ",
                           " Bodega ",
                           " Venta " ,
                           "Transporte",
                           "Articulo",
                           "Cantidad",
                           "Tipo",
                           "Ingresos",
                           "I.V.A.",
                           "Codigo",
                           "Descripcion",
                           "U.M.",
                           "Precio",
                           "Descuento ",
                           "Cantidad",
                           "Embalaje",
                           "Expedicion",
                           "Trasporte",
                           "Puerto",
                           "Inicio trasporte",
                           " Horas ",
                           "Imponible",
                           "Impuesto",
                           "Cantidad de Administraci&oacute;n",
                           "Peso",
                           "Total",
                           "La fecha de inicio del transporte no es correcta!",
                           "La fecha de inicio del transporte no puede ser anterior a la fecha de edici&oacute;n!",
                           "No renglones para poder emitir el documento!",
                           "Esta tratando de modificar el DdT con una fecha anterior a aquella del DdT con numero precedente!",
                           "Esta tratando de modificar el DdT con una fecha posterior a aquella del DdT con numero succesivo!",
                           "Esta tratando de modificar el documento con una fecha anterior a aquel del mismo tipo de documento con numero antecedente!" ,
                           "Est&aacute;s intentando modificar el documento con una fecha sucesiva a aquello del mismo tipo de documento con n&uacute;mero sucesivo!" ,
                           "La fecha de emisi&oacute;n no puede ser anterior a aquella del &uacute;ltimo DdT emetido!",
                           "La fecha de emisi&oacute;n no puede ser anterior a aquella del &uacute;ltimo documento del mismo tipo emitido!",
                           "La fecha de emisi&oacute;n no es correcta!",
                           "Usted no ha seleccionado el cliente!",
                           "Usted no ha seleccionado un método de pago!",
                           "Una fila no tiene ninguna descripci&oacute;n!",
                           "Una l&iacute;nea es sin la unidad de medida!",
                           "Causal de bodega",
                           "Peso neto",
                           "Peso bruto",
                           "N.paquetes",
                           "Volumen",
                           "Comisiones",
                           "Desea cambiar un D.d.T. ya facturado!",
                           "Este documento ya ha sido contabilizado!",
                           'speban'=>"Gastos de recaudaci&oacute;n",
                           'speban_title'=>'Gastos de recaudaci&oacute;n no documentado/prorratas',
                           'traspo_title'=>'Gastos  de trasporte no documentado',
                           'stamp'=>'Sellos',
                           'id_agente'=>"Agente de venta",
                           'print_total'=>"Print total",
                           'print_total_value'=>array(0=>'No',1=>'Yes'),
                           'delivery_time'=>"Delivery_days",
                           'day_of_validity'=>"Days of validity"
                           ),
                    "report_contract.php" =>
                    array( 'title'=>'Reporte de los contratos concluidos',
                           'vat_section'=>' de IVA seccion n.',
                           'link1'=>'Insertar nuevo contrato',
                           'link2'=>'Crear factura/boleta de contratos',
                           'id'=>'ID',
                           'date'=>'Fecha',
                           'number'=>'Numero',
                           'customer'=>'Cliente',
                           'current_fee'=>'Honorario Actual'
                           ),
                    "admin_contract.php" =>
                    array( 'title'=>'Administracion de contrato',
                           'ins_this'=>'Insertar nuevo contrato con ',
                           'upd_this'=>'Actualizar contrato concluido con ',
                           'errors'=>array('Fecha de estipulacion no correcta',
                                           'Fecha de inicio per&iacute;odo contractual no correcta',
                                           'Fecha &uacute;ltima adecuaci&oacute;n del canon no es correcta',
                                           'Fecha de estipulaci&oacute;n sucesiva a aquella de comienzo',
                                           'Fecha de inicio posterior al ultimo ajuste anual ',
                                           'No ha seleccionado un cliente',
                                           'No seleccionado un método de pago',
                                           'Por lo menos una l&iacute;nea que falta en la descripci&oacute;n',
                                           'Por lo menos una l&iacute;nea que falta de las unidad de medida',
                                           'El contrato no tiene texto',
                                           'La cuota actual no puede ser cero'
                                          ),
                           'mesg'=>array('La busqueda no dio resultados!',
                                         'Inserte al menos 2 caracteres!',
                                         'Cambiando cliente / proveedor'
                                          ),
                           'address'=>'Dirrecion',
                           'vat_section'=>'Seccion IVA',
                           'doc_type'=> 'Reciboto a ser emitido',
                           'doc_type_value'=>array('VRI'=>'Recibido','FAI'=>'Factura'),
                           'doc_number'=>'Numero de Contrato',
                           'conclusion_date'=>'Fecha de Conclusion',
                           'start_date'=>'Fecha de Inicio',
                           'months_duration'=>'Duraci&oacute;n en Meses',
                           'initial_fee'=>'Honorario Inicial',
                           'periodic_reassessment'=>'Reevaluacion Anual',
                           'bank'=>'Banco de pago',
                           'payment_method'=>'metodo de pago',
                           'periodicity'=>'periodicidad',
                           'periodicity_value'=>array(1=>'mensual',2=>'bimensual',3=>'trimestral',4=>'cuatrimestral',6=>'semestral',12=>'anual'),
                           'tacit_renewal'=>'Renovaci&oacute;n tacita',
                           'current_fee'=>'Honorario Actual',
                           'cod_revenue'=>'Cuanta de ingreso',
                           'vat_code'=>'Codigo de IVA',
                           'body_text'=>'Texto del contrato',
                           'last_reassessment'=>'Ultima reevaluacion',
                           'last_document_date'=>'Ultima fecha de documento',
                           'id_agente'=>'Agente',
                           'provvigione'=>'% commision',
                           'rows_title'=>'Otras objeciones y/ o descripciones',
                           'descri'=>'Description de Objecion ',
                           'unimis'=>'U.M.',
                           'quanti'=>'Cantidad',
                           'price'=>'Precio',
                           'discount'=>'Descuento',
                           'append'=>'Recordatorio Appendice para uso administrativo',
                           'customer'=>'Cliente contratante'
                           ),
                    "delete_contract.php" =>
                    array( 'title'=>'Eliminar contrato ',
                           'alert'=>'¿Est&aacute;s seguro de que deseas eliminar este contrato?'
                           ),
                    "invoice_from_contract.php" =>
                    array( 'title'=>'Crear factura / recibidos de los contratos',
                           'vat_section'=>' de la seccion IVA n.',
                           'on'=>' en ',
                           'period'=>'Periodo',
                           'period_value'=>array(1=>'mes de ',2=>'bimestre ',3=>'trimeste ',4=>'cuatrimestre ',6=>'semestre ',12=>'anualidad '),
                           'n_creation'=>'Numero de doc',
                           'norows'=>'No hay contratos para ser facturados',
                           'expired'=>'Contrato expiro',
                           'err_date'=>'Fecha de ultima factura<br />anterior a la seleccionada',
                           'ref'=>'Desde contrato concluido en fecha '
                           ),
                    "admin_scontr.php" =>
                    array( 'title'=>'Administrar impuesto recibible',
                           'ins_this'=>'emitir un nuevo impuesto recibible en : ',
                           'upd_this'=>'Actualizar impuesto recibible n.',
                           'errors'=>array('Fecha de emision incorrect',
                                           'No se selecciono cleinte',
                                           'No se selecciono metodo de pago',
                                           'Linea sin descripcion',
                                           'Linea sin unidad de medida',
                                           'El total of recibibles no puede ser cero',
                                           'No se puede cobrar el pago automaticamente con un cliente anonimo',
                                           'Codigo fiscal incorrecto ' ,
                                           'QUE NO HAN HECHO EL DIARIO DE CONTABILIDAD DE CAJA REGISTRADORA',
                                           'La cantidad no emite un documento de venta de forma anonima'
                                          ),
                           'customer'=>'Cliente',
                           'search_customer'=>array('No encontrado!',
                                         'Inserte min 2 caracteres!',
                                         'Cambiar customer',
                                         'Cliente Coiche',
                                         ' F.C.:',
                                         'Anonimo'
                                          ),
                           'indspe'=>'Direccion',
                           'seziva'=>'Seccion IVA',
                           'tipdoc'=> 'Tipo de Documento',
                           'listin'=>' n. de lista',
                           'datemi'=>'Fecha de Emision',
                           'caumag'=>'Causal de bodega',
                           'sconto'=>'Descuento',
                           'address'=>'Direccion',
                           'pagame'=>'Pago',
                           'codric'=>'C/ingreso',
                           'codvat'=>'%IVA',
                           'total'=>'Total',
                           'id_agente'=>'Agente',
                           'in_rows_title'=>'inserte fila',
                           'item'=>'Item',
                           'search'=>' buscar ',
                           'in_artsea_value'=>array('C'=>'Codigo de Item', 'B'=>'Codigo de Barra','D'=>'Descripcion'),
                           'tiprig'=> 'Tipo',
                           'tiprig_value'=>array(0=>'Normal',1=>'Oferta',2=>'Descriptivo'),
                           'body_title'=>'cuerpo',
                           'foot_title'=>'totales',
                           'upper_row'=>'Subir!',
                           'codart'=>'Codigo',
                           'descri'=>'Descripcion',
                           'unimis'=>'U.M.',
                           'quanti'=>'Cantidad',
                           'prezzo'=>'Pricio',
                           'provvigione'=>'% Comision',
                           'amount'=>'Cantidad',
                           'sconto'=>'Descuento',
                           'net'=>'Peso neto',
                           'units'=>'Piezas',
                           'volume'=>'Volumen',
                           'taxable'=>'Tributable',
                           'tax'=>'IVA',
                           'confirm'=>'Confirm sent data to ECR?'
                           
                           ),
                    "genera_effett.php" =>
                    array( 'title'=>'Generar los efectos de los documentos tributables',
                           'errors'=>array('No hay documentos que pueden generar efectos con lo seleccionado'
                                          ),
                           'preview'=>'Vista previa de creaci&oacute;n de efecto',
                           'date_reg'=>'Fecha',
                           'protoc'=>'Protocolo/Seccion',
                           'doc_type'=>'Tipo de Document',
                           'doc_type_value'=>array('FAD'=>'Factura Diferida  al cliente',
                                                   'FAI'=>'Factura Inmediata  al cliente',
                                                   'FND'=>'NOTA de Deuda al cliente'
                                                   ),
                           'type'=>'Tipo',
                           'type_value'=>array('B'=>' Recibo Bancario',
                                               'T'=>' Giro',
                                               'V'=>' Payment against notice'
                                               ),
                           'customer'=>'Cliente',
                           'tot'=>'Total',
                           'total_value'=>array('B'=>'Total Recibos Banco',
                                                'T'=>'Total Giros',
                                                'V'=>' Total Payment against notice'
                                               ),
                           'gen'=>'generara',
                           'end'=>'finalizando '
                           ),
                    "distin_effett.php" =>
                    array( 'title'=>'Lista de Papel de cuentas y recibos bancarios',
                           'errors'=>array('No hay efectos en el l&iacute;mite seleccionado',
                                           'Fecha Incorrecta',
                                           'La fecha de inicio es posterior a la final',
                                           'La fecha de emisi&oacute;n es posterior a la inicial'
                                          ),
                           'preview'=>'Vista previa de la lista de papel',
                           'header'=>array('Num'=>'','Tipo'=>'','Fecha de Expiracion'=>'','Cantidad'=>'',
                                            'Cliente/V.R.' =>'','Factura/Cantidad'=>'','Banco/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'Fecha Lista',
                           'bank'=>'Credito Bancario',
                           'date_ini'=>'Fecha de Expiracion Inicial',
                           'date_fin'=>'Fecha de Expiracion Final',
                           'num_ini'=>'Numero Inicial',
                           'num_fin'=>'Numero Final',
                           'period'=>'Seleccione plazos proximos',
                           'period_value'=>'Plazos proximos',
                           'reprint'=>'Rotulados',
                           'reprint_value'=>array('S'=>'Si','N'=>'No'),
                           'type'=>'Tipo de cuenta: ',
                           'type_value'=>array('B'=>'Recibo Bancario','T'=>'Cuenta','V'=>'MAV'),
                           'tot'=>'Total of list'
                           ),
                    "select_filerb.php" =>
                    array( 'title'=>'Creacion de Archivo RiBa (formato CBI)',
                           'errors'=>array('No hay efectos en el l&iacute;mite seleccionado',
                                           'Fecha incorracta',
                                           'La fecha de inicio es posterior a la final',
                                           'La fecha de emisi&oacute;n es posterior a la inicial'
                                          ),
                           'preview'=>'Vista previa de contenido archivo RiBa ( formato CBI)',
                           'header'=>array('Num'=>'','Tipo'=>'','Fecha de Expiracion'=>'','Cantidad'=>'',
                                            'cliente/V.R.' =>'','Factura/Cantidad'=>'','Banco/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'Fecha de lista',
                           'bank'=>'Credito Bancario',
                           'date_ini'=>'Fecha de Expiracion Inicial',
                           'date_fin'=>'Fecha de Expiracion Final',
                           'num_ini'=>'Numero Inicial',
                           'num_fin'=>'Numero Final',
                           'period'=>'Seleccione plazos proximos',
                           'period_value'=>'Plazos proximos',
                           'reprint'=>'Rutulados',
                           'reprint_value'=>array('S'=>'Si','N'=>'No'),
                           'tot'=>'Total del contenido del archivo',
                           'eof'=>'Record with characters at the end of line',
                           'eof_title'=>'Record with characters at the end of line chr 13 e 10'
                           ),
                    "select_filemav.php" =>
                    array( 'title'=>'Creacion de Archivo MAV (formato CBI)',
                           'errors'=>array('No hay efectos en el l&iacute;mite seleccionado',
                                           'Fecha incorracta',
                                           'La fecha de inicio es posterior a la final',
                                           'La fecha de emisi&oacute;n es posterior a la inicial'
                                          ),
                           'preview'=>'Vista previa de contenido archivo MAV ( formato CBI)',
                           'header'=>array('Num'=>'','Tipo'=>'','Fecha de Expiracion'=>'','Cantidad'=>'',
                                            'cliente/V.R.' =>'','Factura/Cantidad'=>'','Banco/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'Fecha de lista',
                           'bank'=>'Credito Bancario',
                           'date_ini'=>'Fecha de Expiracion Inicial',
                           'date_fin'=>'Fecha de Expiracion Final',
                           'num_ini'=>'Numero Inicial',
                           'num_fin'=>'Numero Final',
                           'period'=>'Seleccione plazos proximos',
                           'period_value'=>'Plazos proximos',
                           'reprint'=>'Rutulados',
                           'reprint_value'=>array('S'=>'Si','N'=>'No'),
                           'tot'=>'Total del contenido del archivo'
                           ),
                    "error_msg.php" =>
                    array( 'admin_scontr'=>array(0=>'Advertencia!<br />No tiene privilegios para enviar datos a la caja registradora (ECR), p&oacute;ngase en contacto con su administrador para cambiar la configuraci&oacute;n de la tabla gaz_cash_register')
                          ),
                    "report_scontr.php" =>
                    array( 'title'=>'Informe de crédito fiscal',
                           'seziva'=>' de la secci&oacute;n de IVA n.',
                           'link1'=>'Emitir un nuevo crédito fiscal',
                           'link2'=>'Ejecutar el cierre diario de la caja registradora',
                           'id'=>'ID',
                           'date'=>'Fecha',
                           'number'=>'Numero',
                           'invoice'=>'Factura adjuntas',
                           'status'=>'Estado',
                           'status_value'=>array(0=>'Emitida',1=>'Registrada'),
                           'send'=>'Retransmitir a ECR',
                           'amount'=>'Amount'
                           ),
                    "report_broven.php" =>
                    array( 'title'=>'Las cotizaciones y pedidos',
                         'mail_alert0'=>'Invio documento con email',
                         'mail_alert1'=>'Hai scelto di inviare una e-mail all\'indirizzo: ',
                         'mail_alert2'=>'con allegato il seguente documento:',
                           'title_value'=>array('VPR'=>'Las citas a los clientes',
                                          'VOR'=>'Pedidos de los clientes',
                                          'VOW'=>'Los pedidos de la p&aacute;gina web'),
                           'link_title' =>array('VPR'=>'Nuevas citas con los clientes',
                                          'VOR'=>'Nuevo Pedidos de los clientes',
                                          'VOW'=>'Obtener Pedidos de la p&aacute;gina web'),
                           'link_value' =>array('VPR'=>'admin_broven.php?Insert&tipdoc=VPR',
                                          'VOR'=>'admin_broven.php?Insert&tipdoc=VOR',
                                          'VOW'=>'import_gaziecart.php'),
                           'issue_ord'=>'Proceso de pedidos',
                           'id'=>'ID',
                           'type'=>'Tipo',
                           'type_value' =>array('VPR'=>'Citas',
                                          'VOR'=>'Pedidos',
                                          'VOW'=>'Pedidos WEB'),
                           'date'=>'Fecha',
                           'number'=>'N&uacute;mero',
                           'issue'=>'Procesa',
                           'status'=>'Estado',
                           'status_value'=>array(0=>'',1=>'PROCESA')
                           ),
                    "resend_to_ecr.php" =>
                    array( 'title'=>'Retransmision de datos a caja registradora',
                           'head'=>'Reemitir el recibo n.',
                           'on'=>' en: ',
                           'total'=>'Cantidad TOTAL',
                           'message'=>" ADVERTENCIA!!! <br />Est&aacute; intentando volver a emitir un recibo tributario expedido, esto no es normal.<br />S&oacute;lo cuando se hayan tenido problemas que han impedido la transmisi&oacute;n de datos a la registradora en el proceso de expedici&oacute;n de una nueva boleta que es correcto.<br />Antes de proceder le recomendamos  hacerlo manualmente en la registradora para asegurarse de que no se deja en un estado de espera y luego no pudo completar la emision",
                           'submit'=>'Enviar de todas formas'
                           ),
                    "close_ecr.php" =>
                    array( 'title1'=>'Realizar el cierre de la caja registradora',
                           'title2'=>' y trasladar de los recibos emitidos al libro',
                           'message'=>"ADVERTENCIA!!! <br />No hay boletas emitidas y  no cerradas/contabilizadas en esta caja registradora",
                           'date'=>'Fecha',
                           'num'=>'Numero',
                           'sez'=>'Seccion IVA',
                           'customer'=>'Cliente',
                           'anony'=>'Anonimo',
                           'importo'=>'Cantidad'
                           ),
                    "accounting_documents.php" =>
                    array( 'title'=>'Crear movimientos contables de los documentos tributables',
                           'errors'=>array('Fecha Incorrecta',
                                           'No hay documentos para ser escritos en lo seleccionado'
                                          ),
                           'vat_section'=>' de seccion de IVA n.',
                           'date'=>'hasta :',
                           'type'=>'Registro IVA ',
                           'type_value'=>array('F'=>'de facturas de ventas','V'=>'de cargos'),
                           'proini'=>'Protocolo Initial',
                           'profin'=>'Protocolo Final',
                           'preview'=>'Vista previa Contabilidad',
                           'date_reg'=>'Fecha',
                           'protoc'=>'Protocolo',
                           'doc_type'=>'Tipo',
                           'doc_type_value'=>array('FAD'=>'FACTURA DIFERIDA AL CLIENTE',
                                                   'FAI'=>'FACTURA INMEDITA AL CLIENTE',
                                                   'FNC'=>'NOTA DE CREDITO AL CLIENTE',
                                                   'FND'=>'NOTA DE DEUDA AL CLIENTE',
                                                   'VCO'=>'HONORARIOS',
                                                   'VRI'=>'RECIBIDOS',
                                                   'AFA'=>'FACTURA DE COMPRA',
                                                   'AFC'=>'NOTA DE CREDITO DE LA COMPRA',
                                                   'AFD'=>'NOTA DE DEUDA DE LA COMPRA'
                                                   ),
                           'customer'=>'Cliente/Proveedor',
                           'taxable'=>'Tributable',
                           'vat'=>'IVA',
                           'stamp'=>'Sellos en las Cuentas',
                           'tot'=>'Total'
                           ),
                    "import_gaziecart.php" =>
                    array( 'title'=>'Importazione ordini web provenienti da GAzieCart',
                           'errors'=>array('Non ci sono ordini da importare dalla casella e-mail'
                                          ),
                           'email'=>'Direcci&oacute;n para recibir &oacute;rdenes: ',
                           'pass'=>'Contrase&ntilde;a utilizada para acceder a: ',
                           'server'=>'Direcci&oacute;n del servidor: ',
                           'name'=>'Orden WEB',
                           'amount'=>'Totales de mercanc&iacute;as',
                           'tot'=>'TOTALES ',
                           'tax'=>'IVA',
                           'des1'=>' en el sitio web: ',
                           'mesg'=>array('La busqueda no dio resultados!',
                                         'Inserte al menos 2 caracteres!',
                                         'Cambiando cliente / proveedor'
                                          ),
                           'errors'=>array('Seleccione el cliente!',
                                           'Seleccione el tipo de pago',
                                           'Habilitar la extensi&oacute;n php_imap en php.ini para importar pedidos'
                                          ),
                           ),
                    "select_effett.php" =>
                    array( 0=>'Imprimir Cuentas',
                           'title'=>'Select for view and/or print Bank receipts and Bills',
                           'ins_this'=>'Issue bill of exchange to:',
                           'upd_this'=>'Update bill of exchange to: ',
                           'del_this'=>'Borrar cuenta de cambio',
                           'sourcedoc'=>'Documento de origen',
                           'source'=>'Origen',
                           'link_1'=>'Crear cuenta desde Facturas',
                           'link_2'=>'Nueva cuenta de cambio',
                           'link_3'=>'Cuentas de contabildad para cambio',
                           'link_4'=>'Imprimir Cuenta de cambio',
                           'link_5'=>'Cuentas para reporte de cambio',
                           'link_6'=>'Crear archivo Ri.Ba.',
                           'link_7'=>'Crear archivo MAV',
                           'report'=>'Lista de cuentas de cambio',
                           'mesg'=>array('La busqueda no dio resultados!',
                                         'Inserte al menos 2 caracteres!',
                                         'Cambiando cliente'
                                          ),
                           'errors'=>array('Incorrect date!',
                                           'The start date is later than the final',
                                           'Bill start number is greater than the final number!',
                                           'Invoice date is later than issue date!',
                                           'Issue date is later than expiry date!',
                                           'Invalid bill number ',
                                           'Select customer',
                                           'Invalid amount',
                                           'Select the bank support',
                                           'Select payment method'
                                          ),
                           'progre'=>'Number',
                           'type'=>'Tipo',
                           'type_pay'=>array('B'=>'Bank receipt','T'=>'Promissory','V'=>'MAV'),
                           'clfoco'=>'Cliente',
                           'date_emi'=>'Date of Issue',
                           'numfat'=>'Number of invoice',
                           'vat_section'=>'IVA section',
                           'date_doc'=>'Data Factura',
                           'totfat'=>'Factura amount',
                           'salacc'=>'Dep&oacute;sito y el Equilibrio',
                           'salacc_value'=>array('C'=>'Dep&oacute;sito','S'=>'El equilibrio'),
                           'impeff'=>'Cuenta amount',
                           'status'=>'Estado',
                           'date_exp'=>'Expiry date',
                           'account_id'=>'Contabilidad nombre',
                           'pagame'=>'Metodo de pago',
                           'banapp'=>'Bank support',
                           'banacc'=>'Bank credit',
                           'num_ini'=>'Numero de cuenta inicio  ',
                           'date_ini'=>'Fecha de vencimiento inicial ',
                           'num_fin'=>'Numero de cuenta final',
                           'date_fin'=>'Fecha de vencimiento final ',
                           'type_value'=>array('B'=>'Recibos bancarios','T'=>'Giros-cuentas','V'=>'MAV'),
                           'header'=>array('Num'=>'','Fecha de vencimiento'=>'','Cantidad'=>'',
                                            'Cliente' =>'','Factura'=>'','Banco'=>''
                                           )
                           ),
                    "select_partner_status.php" =>
                    array( 'title'=>'Selezione per la visualizzazzione e/o la stampa dello scadenzario dei clienti',
                           'print_title'=>'SUPPLIERS DATETABLE ',
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'err'=>'Ci sono degli errori che impediscono la stampa'
                                          ),
                           'date_ini'=>'Data di riferimento ',
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni di esposizione' =>'','Stato'=>''
                                           ),
                            'status_value'=>array(0=>'APERTA',1=>'CHIUSA',2=>'ESPOSTA',3=>'SCADUTA',9=>'ANTICIPO')
                           ),
                    "report_schedule.php" =>
                    array( 'title'=>'Lista dei movimenti delle partite',
                           'header'=>array( 'ID'=>'id',
                                            'Identificativo partita' => "id_tesdoc_ref",
                                            'Movimento contabile apertura (documento)' => "id_rigmoc_doc",
                                            'Movimento contabile chiusura (pagamento)' => "id_rigmoc_pay",
                                            'Importo' => "amount",
                                            'Scadenza' => "expiry"
                                            ),
                           ),
                    "select_schedule.php" =>
                    array( 'title'=>'Selezione per la visualizzazzione e/o la stampa delle partite aperte',
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente/fornitore'
                                          ),
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'Non sono stati trovati movimenti!'
                                          ),
                           'account'=>'Cliente ',
                           'orderby'=>'Ordina per: ',
                           'orderby_value'=>array(0=>'Scadenza crescente',1=>'Scadenza decrescente',
                                                  2=>'Cliente crescente',3=>'Cliente decrescente'
                                           ),
                           'header'=>array('Cliente'=>'','ID Partita'=>'','Status'=>'','Mov.Cont.'=>'','Descrizione'=>'',
                                            'N.Doc.'=>'','Data Doc.' =>'','Data Reg.' =>'','Dare'=>'','Avere'=>'',
                                            'Scadenza'=>''
                                           ),
                           'status_value'=>array(0=>'Chiusa',1=>'Aperta'),
                           ),
                    "delete_schedule.php" =>
                    array( 'title'=>'Cancellazione movimenti chiusi dello scadenziario',
                           'ragsoc'=>'Cliente',
                           'id_tesdoc_ref'=>'Identificativo partita',
                           'descri'=> 'Descrizione'
                           ),
                    "select_evaord.php" =>
                    array( 'title'=>'Order picking of customer',
                           'errors'=>array('Non &egrave; stato selezionato un cliente',
                                           'Non ci sono righi',
                                           'Non ci sono righi inevasi per generare il documento selezionato',
                                           'Select payment method',
                                           'Incorrect date of issue',
                                           'Incorrect start date of transport',
                                           'Start date of transport prior to the issue date',
                                           'YOU HAVE NOT DONE THE CLOSING DAY OF THE CASH REGISTER TO DO BEFORE YOU GIVE A NEW ONE!'
                                          ),
                           'customer'=>'Customer',
                           'search_customer'=>array('The search yielded no results!',
                                         'Insert at least 2 characters!',
                                         'Changing customer',
                                         'Choice customer',
                                         ' F.C.:',
                                         'Anonymous'
                                          ),
                           'indspe'=>'Address',
                           'seziva'=>'VAT Section',
                           'destin'=>'Destination',
                           'banapp'=>'Bank',
                           'listin'=>'Price list n.',
                           'datemi'=>'Date ',
                           'initra'=>'Start date of transport ',
                           'traspo'=>'Transport ',
                           'spediz'=>'Delivery ',
                           'portos'=>'Rendered port ',
                           'imball'=>'Pack ',
                           'vettor'=>'Shippers ',
                           'sconto'=>'Discount',
                           'pagame'=>'Payment',
                           'preview_title'=>'BACKLOG:',
                           'from'=>'from Order n.',
                           'del'=>' of ',
                           'upd_ord'=>' Updtae order',
                           'id_agente'=>'Agent ',
                           'codart'=>'Code',
                           'descri'=>'Description',
                           'unimis'=>'M.U.',
                           'quanti'=>'Quantity',
                           'prezzo'=>'Price',
                           'provvigione'=>'%Ag.Com',
                           'amount'=>'Amount',
                           'taxable'=>'Taxable',
                           'issue_fat'=>'Issue with invoice',
                           'issue_ddt'=>'Issue with delivery note',
                           'issue_cor'=>'Issue with ticket',
                           'checkbox'=>'This checkbox must be selected to process the row',
                           'alert1'=>'&sup1; Section IVA choice is not one normally used for the issuance of immediately invoice',
                           'alert2'=>'&sup1; The selected section IVA may not coincide with what will be used for the immediate issuance of the invoice for your choice will be equal to the last emitted.'
                           ),
                    "select_partner_status.php" =>
                    array( 'title'=>'Selezione per la visualizzazzione e/o la stampa dello scadenzario dei clienti',
                           'print_title'=>'SCADENZARIO CLIENTI ',
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'err'=>'Ci sono degli errori che impediscono la stampa'
                                          ),
                           'date_ini'=>'Data di riferimento ',
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>''
                                           ),
                            'status_value'=>array(0=>'APERTA',1=>'CHIUSA',2=>'ESPOSTA',3=>'SCADUTA',9=>'ANTICIPO')
                           ),
                    "customer_payment.php" =>
                    array( 'title'=>'Riscossione credito da cliente (chiusura partita/e)',
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'err'=>'Ci sono degli errori che impediscono la stampa'
                                          ),
                           'partner'=>'Cliente ',
                           'date_ini'=>'Data di registrazione',
                           'target_account'=>"Conto per l'incasso: ",
                           'partner'=>'Cliente: ',
                           'print_ticket'=>"Stampa ricevuta: ",
                           'accbal'=>'Saldo risultante dai movimenti contabili: ',
                           'paymovbal'=>'Saldo risultante dalle partite aperte: ',
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>''
                                           ),
                           'status_value'=>array(0=>'APERTA',1=>'CHIUSA',2=>'ESPOSTA',3=>'SCADUTA',9=>'ANTICIPO'),
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>'', 'Riscuoti'=>''
                                           ),
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente',
                                         'Il saldo contabile è diverso da quello dello scadenzario,<br> se vuoi registrare la riscossione di un documento presente solo in contabilità fallo da qui:',
                                         'Nessun importo è stato riscosso!',
					 "Non è stato selezionato il conto per l'incasso",
                                         'Stai tentando di inserire il pagamento di un cliente senza movimenti'
                                          ),
                           ),
                    "print_customer_payment_receipt.php" =>
                    array( 'title'=>'RISCOSSIONE CREDITO DA ',
                           'id_tesdoc_ref'=>'ID Partita',
                           'descri'=>'Descrizione',
                           'numfat'=>'Numero fattura',
                           'datfat'=>'Data fattura',
                           'amount'=>'Importo riscosso',
                           'tot'=>'TOTALE DELLA RISCOSSIONE',
                           ),
                   "report_fae_sdi.php" =>
                   array(  'title'=>'TRAFFICO DATI FATTURAZIONE ELETTRONICA',
                           'table'=>'Tabella su cui stai lavorando: ',
                           'id'=>'ID',
                           'filename_ori'=>'Nome file primo invio',
                           'numfat'=>'N.<br>fattura',
                           'codice'=>'Cod. cliente',
                           'ragso1'=>'Amministrazione',
                           'exec_date'=>'Data di esecuzione ',
                           'received_date'=>'Data ricezione ',
                           'delivery_date'=>'Data consegna ',
                           'filename_son'=>'Nome file padre',
                           'id_SDI'=>'ID SDI',
                           'filename_ret'=>'Nome file di ritorno',
                           'mail_id'=>'UID della mail',
                           'flux_status'=>'Stato',
                           'flux_status_value'=>array(''=>'Generato',
						                              '#'=>'Non ancora inviata',
                                                      '@'=>'Inviata',
                                                      'NS'=>'Notifica scarto',
                                                      'MC'=>'Mancata Consegna',
                                                      'RC'=>'Ricevuta consegna',
                                                      'NE'=>'Notifica esito',
                                                      'DT'=>'Decorrenza termini'),
                           'progr_ret'=>'Progr.',
                           'flux_descri'=>'Descrizione'
                         )                           
                   );
?>