<?php
/*
 --------------------------------------------------------------------------
                            GAzie - Gestione Azienda
    Copyright (C) 2004-2015 - Antonio De Vincentiis Montesilvano (PE)
         (http://www.devincentiis.it)
           <http://gazie.sourceforge.net>
 --------------------------------------------------------------------------
    Questo programma e` free software;   e` lecito redistribuirlo  e/o
    modificarlo secondo i  termini della Licenza Pubblica Generica GNU
    come e` pubblicata dalla Free Software Foundation; o la versione 2
    della licenza o (a propria scelta) una versione successiva.

    Questo programma  e` distribuito nella speranza  che sia utile, ma
    SENZA   ALCUNA GARANZIA; senza  neppure  la  garanzia implicita di
    NEGOZIABILITA` o di  APPLICABILITA` PER UN  PARTICOLARE SCOPO.  Si
    veda la Licenza Pubblica Generica GNU per avere maggiori dettagli.

    Ognuno dovrebbe avere   ricevuto una copia  della Licenza Pubblica
    Generica GNU insieme a   questo programma; in caso  contrario,  si
    scriva   alla   Free  Software Foundation,  Inc.,   59
    Temple Place, Suite 330, Boston, MA 02111-1307 USA Stati Uniti.
 --------------------------------------------------------------------------
*/

$strScript = array ("admin_client.php" =>
                   array(  'title'=>'Gestione dei clienti',
                           'ins_this'=>'Inserisci un cliente',
                           'upd_this'=>'Modifica  il cliente ',
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia anagrafica'),
                           'errors'=>array('&Egrave; necessario indicare la Ragione Sociale',
                                           '&Egrave; necessario indicare l\'indirizzo',
                                           'Il codice di avviamento postale (CAP) &egrave; sbagliato',
                                           '&Egrave; necessario indicare la citt&agrave;',
                                           '&Egrave; necessario indicare la provincia',
                                           '&Egrave; necessario indicare il sesso',
                                           'L\'IBAN non &egrave; corretto',
                                           'L\'IBAN e la nazione sono diversi',
                                           'Codice fiscale sbagliato per una persona fisica',
                                           'La partita IVA &egrave; formalmente errata!',
                                           'Esiste gi&agrave un Cliente con la stessa Partita IVA',
                                           'Il codice fiscale &egrave; formalmente errato',
                                           'Esiste gi&agrave; un Cliente con lo stesso Codice Fiscale',
                                           'C.F. mancante! In automatico &egrave; stato<br />impostato con lo stesso valore della Partita IVA!',
                                           'E\' una persona fisica, inserire il codice fiscale',
                                           'Esiste una anagrafica con la stessa partita IVA',
                                           'Esiste una anagrafica con lo stesso Codice Fiscale',
                                           '&Egrave; necessario scegliere la modalit&agrave; di pagamento',
                                           'Il codice del cliente &egrave; gi&agrave; esistente, riprova l\'inserimento con quello proposto (aumentato di 1)',
                                           'La data di nascita &egrave; sbagliata',
                                           'Indirizzo email formalmente sbagliato'
                                          ),
                           'link_anagra'=>' Clicca sotto per inserire l\'anagrafica esistente sul piano dei conti',
                           'codice'=>"Codice ",
                           'ragso1'=>"Ragione Sociale 1",
                           'ragso2'=>"Ragione Sociale 2",
                           'sedleg'=>"Sede legale",
                           'luonas'=>'Luogo di nascita',
                           'datnas'=>'Data di Nascita',
                           'pronas'=>'Provincia di nascita',
                           'counas'=>'Nazione di Nascita',
                           'legrap'=>"Legale rappresentante ",
                           'sexper'=>"Sesso/pers.giuridica ",
                           'sexper_value'=>array(''=>'-','M'=>'Maschio','F'=>'Femmina','G'=>'Giuridica'),
                           'indspe'=>'Indirizzo',
                           'capspe'=>'Codice Postale',
                           'citspe'=>'Citt&agrave; - Provincia',
                           'prospe'=>'Provincia',
                           'country'=>'Nazione',
                           'id_language'=>'Lingua',
                           'id_currency'=>'Valuta',
                           'telefo'=>'Telefono',
                           'fax'=>'Fax',
                           'cell'=>'Cellulare',
                           'codfis'=>'Codice Fiscale',
                           'pariva'=>'Partita I.V.A.',
                           'e_mail'=>'e mail',
                           'id_agente'=>'Agente',
                           'codpag'=>'Modalit&agrave; di pagamento *',
                           'sconto'=>'% Sconto da apllicare',
                           'banapp'=>'Banca d\'appoggio',
                           'portos'=>'Porto - Resa',
                           'spediz'=>'Spedizione',
                           'imball'=>'Imballo',
                           'listin'=>'Listino da applicare',
                           'id_des'=>'Destinazione &rArr; da anagrafica',
                           'destin'=>'Destinazione &rArr; descrizione libera',
                           'iban'=>'IBAN',
                           'maxrat'=>'Massimo importo delle rate',
                           'ragdoc'=>'Raggruppamento documenti',
                           'addbol'=>'Addebito spese bolli',
                           'speban'=>'Addebito spese bancarie',
                           'spefat'=>'Addebito spese di fatturazione',
                           'stapre'=>'Stampa prezzi su D.d.T.',
                           'op_type'=>'Tipologia operazioni',
                           'op_type_value'=>array(1=>'Cessione di beni',2=>'Prestazione di servizi'),
                           'allegato'=>'Spesometro - Elenco Clienti',
                           'yn_value'=>array('S'=>'Si','N'=>'No'),
                           'aliiva'=>'Riduzione I.V.A.',
                           'ritenuta'=>'% Ritenuta',
                           'status'=>'Visibilit&agrave; alla ricerca',
                           'status_value'=>array(''=>'Attiva','HIDDEN'=>'Disabilitata'),
                           'annota'=>'Annotazioni',
                           'fe_cod_univoco'=>'Cod.Univoco Destinatario (fatt.elettronica)'
                         ),
                   "report_docven.php" =>
                   array('title'=>'Lista dei documenti di vendita',
                         'mail_alert0'=>'Invio documento con email',
                         'mail_alert1'=>'Hai scelto di inviare una e-mail all\'indirizzo: ',
                         'mail_alert2'=>'con allegato il seguente documento di vendita:',
                         'fae_alert0'=>'Generazione documento FAE',
                         'fae_alert1'=>'Hai scelto di generare la fattura elettronica ',
                         'fae_alert2'=>'',
                         'report_alert0'=>'Mostra tutti i documenti',
                         'report_alert1'=>'Sicuro di voler mostrare tutti i documenti?'
                         ),
                    "admin_agenti.php" =>
                   array(  "Agenti di vendita ",
                           "Agente di vendita",
                           "Numero",
                           "Fornitore",
                           "Telefono",
                           "Fax",
                           "% Provvigioni",
                           "Categoria Merceologica",
                           "Articolo",
                           "Percentuale",
                           "Specifiche per ",
                           "gi&agrave; inserito!",
                           "Mancano dei dati necessari per aggiungere un rigo!",
                           "La percentuale delle provvigioni dev'essere maggiore di 0.01!",
                           "Stai tentando di inserire un agente senza collegarlo ad un fornitore!",
                           "Non &egrave; stato inserito il numero di agente",
                           "Stai tentando di inserire un fornitore che &egrave; gi&agrave; un agente!",
                           "Stai tentando di inserire un numero di agente che gi&agrave; esiste!",
                           "Stai elimimando un agente!",
                           "Lista Provvigioni",
                           'title'=>'Gestione degli Agenti di vendita',
                           'ins_this'=>'Inserisci un nuovo agente di vendita'
                           ),
                    "select_provvigioni.php" =>
                   array(  "Selezione per Stampa lista Provvigioni",
                           "Agente di vendita",
                           "Tutti gli Agenti",
                           "Inserire min. 2 caratteri!",
                           "Non &egrave; stato trovato nulla!",
                           "Data periodo inizio",
                           "Data periodo fine"
                           ),
                    "admin_docven.php" =>
                   array(  array("DDT" => "D.d.T. di Vendita",
                                 "FAD" => "D.d.T. di Vendita",
                                 "FAI" => "Fattura Immediata",
                                 "FAP" => "Parcella",
                                 "FNC" => "Nota Credito a Cliente",
                                 "FND" => "Nota Debito a Cliente",
                                 "VCO" => "Vendita Corrispettivo",
                                 "VRI" => "Ricevuta"
                                 ),
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente/fornitore'),
                           " corpo ",
                           " piede ",
                           " Tira su ",
                           " Sezione ",
                           " Indirizzo ",
                           " Data ",
                           " Listino ",
                           " Pagamento ",
                           " Banca ",
                           " Destinazione ",
                           " Causale ",
                           " magazzino ",
                           " vendita " ,
                           "Vettore",
                           "Articolo",
                           "Quantit&agrave;",
                           "Tipo",
                           "Ricavo",
                           "I.V.A.",
                           "Codice",
                           "Descrizione",
                           "U.M.",
                           "Prezzo",
                           "Sconto",
                           "Importo",
                           "Imballo",
                           "Spedizione",
                           "Trasporto",
                           "Porto",
                           "Inizio trasporto",
                           " ore ",
                           "Imponibile",
                           "Imposta",
                           "Tot.Corpo",
                           "Peso",
                           "Totale",
                           "La data di inizio trasporto non &egrave; corretta!",
                           "La data di inizio trasporto non pu&ograve; essere precedente alla data di emissione!",
                           "Non ci sono righi per poter emettere il documento!",
                           "Stai tentando di modificare il DdT con una data antecedente a quella del DdT con numero precedente!",
                           "Stai tentando di modificare il DdT con una data successiva a quella del DdT con numero successivo!",
                           "Stai tentando di modificare il documento con una data antecedente a quello dello stesso tipo di documento con numero precedente!" ,
                           "Stai tentando di modificare il documento con una data successiva a quello dello stesso tipo di documento con numero successivo!" ,
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo DdT emesso!",
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo documento dello stesso tipo emesso!",
                           "La data di emissione non &egrave; corretta!",
                           "Non hai selezionato il cliente!",
                           "Non hai selezionato la modalit&agrave; di pagamento!",
                           "Un rigo &egrave; senza la descrizione!",
                           "Un rigo &egrave; senza l'unit&agrave; di misura!",
                           "Causale mag.",
                           "Peso netto",
                           "Peso lordo",
                           "N.Colli",
                           "Volume",
                           "Provvigioni",
                           "Vuoi modificare un D.d.T. gi&agrave; fatturato!",
                           "Questo documento &egrave; gi&agrave; stato contabilizzato!",
                           'speban'=>"Spese incasso",
                           'speban_title'=>'Spese incasso non documentate/rate',
                           'traspo_title'=>'Spese trasporto non documentate',
                           'stamp'=>'Bolli su tratte',
                           'ritenuta'=>'Ritenuta ',
                           'netpay'=>'Netto a pagare',
                           'id_agente'=>"Agente di vendita",
                           'in_artsea'=>'Ricerca per ',
                           'vat_constrain'=>'(forza) IVA al ',
                           'taxstamp'=>'Bollo',
                           'virtual_taxstamp'=>'Modo',
                           'virtual_taxstamp_value'=>array(0=>'No',1=>'Materiale',2=>'Virtuale',3=>'Virtuale senza addebito'),

                           ),
                    "select_docforprint.php" =>
                   array(  array(1 => "D.d.T. di Vendita",
                                 2 => "Fattura Differita",
                                 3 => "Fattura Immediata Accompagnatoria",
                                 4 => "Fattura Immediata Semplice",
                                 5 => "Nota Credito a Cliente",
                                 6 => "Nota Debito a Cliente",
                                 7 => "Ricevuta"),
                           " nella sezione ",
                           "Data",
                           "Protocollo",
                           "Numero",
                           " inizio",
                           " fine",
                           "Tipo ",
                           "Selezione Cliente ",
                           "inserire min. 2 caratteri!",
                           "Tutti i clienti!",
                           "Non &egrave; stato trovato nulla!",
                           "Il numero inizio dev'essere maggiore di zero !",
                           "Il numero fine dev'essere maggiore o uguale al numero inizio !",
                           "Il protocollo inizio dev'essere maggiore di zero !",
                           "Il protocollo fine dev'essere maggiore o uguale al protocollo inizio !",
                           "La data inizio non &egrave; corretta !",
                           "La data fine non &egrave; corretta !",
                           "La data fine dev'essere successiva a quella di inizio !",
                           "Non ci sono documenti stampabili negli intervalli selezionati !"
                           ),
                    "admin_broven.php" =>
                   array( array("VPR" => "Preventivo a Cliente","VOR" => "Ordine da Cliente","VOW" => "Ordine dal Web"),
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente/fornitore'),
                           " corpo ",
                           " piede ",
                           " Tira su ",
                           " Sezione ",
                           " Indirizzo ",
                           " Data ",
                           " Listino ",
                           " Pagamento ",
                           " Banca ",
                           " Destinazione ",
                           " Causale ",
                           " magazzino ",
                           " vendita " ,
                           "Vettore",
                           "Articolo",
                           "Quantit&agrave;",
                           "Tipo",
                           "Ricavo",
                           "I.V.A.",
                           "Codice",
                           "Descrizione",
                           "U.M.",
                           "Prezzo",
                           "Sconto",
                           "Importo",
                           "Imballo",
                           "Spedizione",
                           "Trasporto",
                           "Porto",
                           "Inizio trasporto",
                           " ore ",
                           "Imponibile",
                           "Imposta",
                           "Tot.Corpo",
                           "Peso",
                           "Totale",
                           "La data di inizio trasporto non &egrave; corretta!",
                           "La data di inizio trasporto non pu&ograve; essere precedente alla data di emissione!",
                           "Non ci sono righi per poter emettere il documento!",
                           "Stai tentando di modificare il DdT con una data antecedente a quella del DdT con numero precedente!",
                           "Stai tentando di modificare il DdT con una data successiva a quella del DdT con numero successivo!",
                           "Stai tentando di modificare il documento con una data antecedente a quello dello stesso tipo di documento con numero precedente!" ,
                           "Stai tentando di modificare il documento con una data successiva a quello dello stesso tipo di documento con numero successivo!" ,
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo DdT emesso!",
                           "La data di emissione non pu&ograve; essere antecedente a quella dell'ultimo documento dello stesso tipo emesso!",
                           "La data di emissione non &egrave; corretta!",
                           "Non hai selezionato il cliente!",
                           "Non hai selezionato la modalit&agrave; di pagamento!",
                           "Un rigo &egrave; senza la descrizione!",
                           "Un rigo &egrave; senza l'unit&agrave; di misura!",
                           "Causale mag.",
                           "Peso netto",
                           "Peso lordo",
                           "N.Colli",
                           "Volume",
                           "Provvigioni",
                           "Vuoi modificare un D.d.T. gi&agrave; fatturato!",
                           "Questo documento &egrave; gi&agrave; stato contabilizzato!",
                           'speban'=>"Spese incasso",
                           'speban_title'=>'Spese incasso non documentate/rate',
                           'traspo_title'=>'Spese trasporto non documentate',
                           'stamp'=>'Bolli',
                           'id_agente'=>"Agente di vendita",
                           'print_total'=>"Stampa totale",
                           'print_total_value'=>array(0=>'No',1=>'Si'),
                           'delivery_time'=>"Tempi di consegna",
                           'day_of_validity'=>"Giorni di validità ",
                           'vat_constrain'=>'(forza) IVA al ',
                           'taxstamp'=>'Bollo',
                           'virtual_taxstamp'=>'Modo',
                           'virtual_taxstamp_value'=>array(0=>'No',1=>'Materiale',2=>'Virtuale'),

                           ),
                    "report_contract.php" =>
                    array( 'title'=>'Elenco dei contratti stipulati',
                           'vat_section'=>' della sezione IVA n.',
                           'link1'=>'Stipula un nuovo contratto',
                           'link2'=>'Genera fatture/ricevute dai contratti',
                           'id'=>'ID',
                           'date'=>'Data',
                           'number'=>'Numero',
                           'customer'=>'Cliente',
                           'current_fee'=>'Canone corrente'
                           ),
                    "admin_contract.php" =>
                    array( 'title'=>'Gestione dei contratti',
                           'ins_this'=>'Stipula un nuovo contratto con ',
                           'upd_this'=>'Modifica contratto stipulato con ',
                           'errors'=>array('Data di stipula non corretta',
                                           'Data inizio periodo contrattuale non corretta',
                                           'Data ultimo adeguamento del canone non corretta',
                                           'Data di stipula successiva a quella di inizio',
                                           'Data di inizio successiva all\'ultimo adeguamento annuale',
                                           'Non &egrave; stato selezionato un cliente',
                                           'Non &egrave; stato selezionato un metodo di pagamento',
                                           'Almeno un rigo manca della descrizione',
                                           'Almeno un rigo manca della unit&agrave; di misura',
                                           'Il contratto non ha un testo',
                                           'Il canone corrente non pu&ograve; essere zero'
                                          ),
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente/fornitore'),
                           'address'=>'Indirizzo',
                           'vat_section'=>'Sezione IVA',
                           'doc_type'=> 'Ricevuta da emettere',
                           'doc_type_value'=>array('VRI'=>'Ricevuta','FAI'=>'Fattura'),
                           'doc_number'=>'Numero del contratto',
                           'conclusion_date'=>'Data di stipula',
                           'start_date'=>'Data di inizio',
                           'months_duration'=>'Mesi di durata',
                           'initial_fee'=>'Canone iniziale',
                           'periodic_reassessment'=>'Adeguamento annuale',
                           'bank'=>'Banca d\'appoggio',
                           'payment_method'=>'Metodo di pagamento',
                           'periodicity'=>'Periodicità ',
                           'periodicity_value'=>array(1=>'mensile',2=>'bimestrale',3=>'trimestrale',4=>'quadrimestrale',6=>'semestrale',12=>'annuale'),
                           'tacit_renewal'=>'Tacito rinnovo',
                           'current_fee'=>'Canone corrente',
                           'cod_revenue'=>'Conto ricavo',
                           'vat_code'=>'Aliquota IVA',
                           'body_text'=>'Testo del contratto',
                           'last_reassessment'=>'Ultimo adeguamento',
                           'last_document_date'=>'Ultima fattura/ricevuta',
                           'id_agente'=>'Agente',
                           'provvigione'=>'% provvigione',
                           'rows_title'=>'Eventuali altri addebiti e/o descrizioni',
                           'descri'=>'Descrizione addebito',
                           'unimis'=>'U.M.',
                           'quanti'=>'Quantità ',
                           'price'=>'Prezzo',
                           'discount'=>'Sconto',
                           'append'=>'Appendice di promemoria ad uso amministrativo',
                           'customer'=>'Cliente contraente'
                           ),
                    "delete_contract.php" =>
                    array( 'title'=>'Eliminazione contratto ',
                           'alert'=>'Sei sicuro di voler eliminare il seguente contratto?'
                           ),
                    "invoice_from_contract.php" =>
                    array( 'title'=>'Genera le fatture/ricevute da contratti',
                           'vat_section'=>' della sezione IVA n.',
                           'on'=>'alla data del',
                           'period'=>'Periodo : ',
                           'period_value'=>array(1=>'mese di ',2=>'bimestre ',3=>'trimeste ',4=>'quadrimestre ',6=>'semestre ',12=>'annualità  '),
                           'n_creation'=>'N. doc. da generare',
                           'norows'=>'Non ci sono contratti da fatturare',
                           'expired'=>'Contratto scaduto',
                           'err_date'=>'Data ultima fattura<br />precedente quella selezionata',
                           'ref'=>'Da contratto stipulato in data '
                           ),
                    "report_scontr.php" =>
                    array( 'title'=>'Scontrini fiscali emessi',
                           'seziva'=>' della sezione IVA n.',
                           'link1'=>'Emetti uno scontrino fiscale',
                           'link2'=>'Esegui la chiusura giornaliera del registratore di cassa',
                           'id'=>'ID',
                           'date'=>'Data',
                           'number'=>'Numero',
                           'invoice'=>'Fattura allegata',
                           'status'=>'Stato',
                           'status_value'=>array(0=>'EMESSO',1=>'CONTABILIZZATO'),
                           'send'=>'Invia nuovamente all\'ECR',
                           'amount'=>'Importo'
                           ),
                    "report_broven.php" =>
                    array( 'title'=>'Preventivi e ordini',
                         'mail_alert0'=>'Invio documento con email',
                         'mail_alert1'=>'Hai scelto di inviare una e-mail all\'indirizzo: ',
                         'mail_alert2'=>'con allegato il seguente documento:',
                         'title_value'=>array('VPR'=>'Preventivi a clienti',
                                          'VOR'=>'Ordini dei clienti',
                                          'VOW'=>'Ordini dal web'),
                           'link_title' =>array('VPR'=>'Nuovo Preventivo a cliente',
                                          'VOR'=>'Nuovo Ordine da cliente',
                                          'VOW'=>'Acquisisci Ordini dal web'),
                           'link_value' =>array('VPR'=>'admin_broven.php?Insert&tipdoc=VPR',
                                          'VOR'=>'admin_broven.php?Insert&tipdoc=VOR',
                                          'VOW'=>'import_gaziecart.php'),
                           'issue_ord'=>'Evadi Ordini',
                           'id'=>'ID',
                           'type'=>'Tipo',
                           'type_value' =>array('VPR'=>'Preventivo',
                                          'VOR'=>'Ordine',
                                          'VOW'=>'Ordine web'),
                           'date'=>'Data',
                           'number'=>'Numero',
                           'issue'=>'Evadi',
                           'status'=>'Stato',
                           'status_value'=>array(0=>'',1=>'EVASO')
                           ),
                    "resend_to_ecr.php" =>
                    array( 'title'=>'Ritrasmetti i dati al registratore di cassa',
                           'head'=>'Riemetti scontrino n.',
                           'on'=>' su: ',
                           'total'=>'Importo TOTALE',
                           'message'=>"ATTENZIONE!!!<br />Stai tentando di riemettere uno scontrino fiscale gi&agrave; emesso, questo non &egrave; normale. Solo quando si sono verificati dei problemi che hanno impedito la trasmissione dei dati al registratore in fase di emissione di un nuovo scontrino questa operazione &egrave; giustificata.<br />Prima di procedere consigliamo di agire manualmente sul registratore per accertarsi che non sia rimasto in uno stato di attesa e quindi non abbia completato l'emissione",
                           'submit'=>'Conferma comunque'
                           ),
                    "close_ecr.php" =>
                    array( 'title1'=>'Effettua la chiusura del registratore di cassa ',
                           'title2'=>' e contabilizza gli scontrini emessi.',
                           'message'=>"ATTENZIONE!!! <br />Non risultano scontrini emessi e non chiusi/contabilizzati su questo registratore di cassa",
                           'date'=>'Data',
                           'num'=>'Numero',
                           'sez'=>'Sez.IVA',
                           'customer'=>'Cliente',
                           'anony'=>'Anonimo',
                           'importo'=>'Importo'
                           ),
                    "admin_scontr.php" =>
                    array( 'title'=>'Gestione degli scontrini',
                           'ins_this'=>'emetti un nuovo scontrino fiscale su : ',
                           'upd_this'=>'Modifica lo scontrino fiscale n.',
                           'errors'=>array('Data di emissione non corretta',
                                           'Non &egrave; stato selezionato un cliente',
                                           'Non &egrave; stato selezionato un metodo di pagamento',
                                           'Un rigo manca della descrizione',
                                           'Un rigo manca della unit&agrave; di misura',
                                           'Il totale dello scontrino non pu&ograve; essere zero',
                                           'Il pagamento non pevede l\'incasso automatico pur essendo un cliente anonimo',
                                           'Il codice fiscale &egrave; formalmente errato',
                                           'NON HAI ESEGUITO LA CHIUSURA GIORNALIERA DEL REGISTRATORE DI CASSA<BR /> FALLO PRIMA DI EMETTERNE UNO!!!',
                                           'L\'importo non consente di emettere un documento di vendita anonimo'
                                          ),
                           'customer'=>'Cliente',
                           'search_customer'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente',
                                         'Scegli un cliente',
                                         ' C.F.:',
                                         'Anonimo'
                                          ),
                           'indspe'=>'Indirizzo',
                           'seziva'=>'Sezione IVA',
                           'tipdoc'=> 'Tipo di documento',
                           'listin'=>'Listino n.',
                           'datemi'=>'Data emissione',
                           'caumag'=>'Causale magazz.',
                           'sconto'=>'Sconto',
                           'address'=>'Indirizzo',
                           'pagame'=>'Pagamento',
                           'codric'=>'C/ricavo',
                           'codvat'=>'%IVA',
                           'vat_constrain'=>'(forza) IVA al ',
                           'total'=>'Totale',
                           'id_agente'=>'Agente',
                           'in_rows_title'=>'inserimento rigo',
                           'item'=>'Articolo',
                           'search'=>' ricerca per ',
                           'in_artsea_value'=>array('C'=>'Codice articolo', 'B'=>'Codice a barre','D'=>'Descrizione'),
                           'tiprig'=> 'Tipo',
                           'tiprig_value'=>array(0=>'Normale',1=>'Forfait',2=>'Descrittivo'),
                           'body_title'=>'corpo',
                           'foot_title'=>'totali',
                           'upper_row'=>'Tira su!',
                           'codart'=>'Codice',
                           'descri'=>'Descrizione',
                           'unimis'=>'U.M.',
                           'quanti'=>'Quantità ',
                           'prezzo'=>'Prezzo',
                           'provvigione'=>'%Prov',
                           'amount'=>'Importo',
                           'sconto'=>'Sconto',
                           'net'=>'Peso netto',
                           'units'=>'N.Colli',
                           'volume'=>'Volume',
                           'taxable'=>'Imponibile',
                           'tax'=>'I.V.A.',
                           'confirm'=>'Confermi invio dati al registratore di cassa?'
                           ),
                    "genera_effett.php" =>
                    array( 'title'=>'Genera gli effetti a partire dai documenti fiscali',
                           'errors'=>array('Non ci sono documenti che possono generare effetti nell\'intervallo selezionato'
                                          ),
                           'preview'=>'Anteprima della generazione degli effetti',
                           'date_reg'=>'Data',
                           'protoc'=>'Protocollo/Sez',
                           'doc_type'=>'Tipo documento',
                           'doc_type_value'=>array('FAD'=>'FATTURA DIFFERITA A CLIENTE',
                                                   'FAI'=>'FATTURA IMMEDIATA A CLIENTE',
                                                   'FND'=>'NOTA DEBITO A CLIENTE'
                                                   ),
                           'type'=>'Tipo effetto',
                           'type_value'=>array('B'=>' la Ricevuta Bancaria',
                                               'T'=>' la Tratta',
                                               'V'=>' il MAV'
                                               ),
                           'customer'=>'Cliente',
                           'tot'=>'Totale',
                           'total_value'=>array('B'=>' Totale delle Ricevute Bancarie',
                                               'T'=>' Totale delle Tratte',
                                               'V'=>' Totale dei MAV'
                                               ),
                           'gen'=>'generer&agrave;',
                           'end'=>'con scadenza '
                           ),
                    "distin_effett.php" =>
                    array( 'title'=>'Stampa distinta cartacea degli effetti per la banca',
                           'errors'=>array('Non ci sono effetti da distintare nell\'intervallo selezionato',
                                           'Data non corretta',
                                           'La data di inizio &egrave; successiva a quella finale',
                                           'La data di emissione &egrave; successiva a quella iniziale'
                                          ),
                           'preview'=>'Anteprima della distinta cartacea degli effetti',
                           'header'=>array('Num'=>'','Tipo'=>'','Scadenza'=>'','Importo'=>'',
                                            'Cliente/P.I.' =>'','Fattura/Importo'=>'','Appoggio/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'Data della distinta',
                           'bank'=>'Banca d\'accredito',
                           'date_ini'=>'Data di scadenza inizio',
                           'date_fin'=>'Data di scadenza fine',
                           'num_ini'=>'Numero inizio',
                           'num_fin'=>'Numero fine',
                           'period'=>'Imposta prossime scadenze',
                           'period_value'=>'Scadenze prossime',
                           'reprint'=>'Distintato',
                           'reprint_value'=>array('S'=>'Si','N'=>'No'),
                           'type'=>'Tipo effetti: ',
                           'type_value'=>array('B'=>'Ricevute Bancarie','T'=>'Tratte','V'=>'MAV'),
                           'tot'=>'Totale della distinta'
                           ),
                    "select_filerb.php" =>
                    array( 'title'=>'Generazione File delle RiBa in formato CBI',
                           'errors'=>array('Non ci sono effetti da distintare nell\'intervallo selezionato',
                                           'Data non corretta',
                                           'La data di inizio &egrave; successiva a quella finale',
                                           'La data di emissione &egrave; successiva a quella iniziale'
                                          ),
                           'preview'=>'Anteprima del contenuto del file RiBa in formato CBI',
                           'header'=>array('Num'=>'','Tipo'=>'','Scadenza'=>'','Importo'=>'',
                                            'Cliente/P.I.' =>'','Fattura/Importo'=>'','Appoggio/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'Data della distinta',
                           'bank'=>'Banca d\'accredito',
                           'date_ini'=>'Data di scadenza inizio',
                           'date_fin'=>'Data di scadenza fine',
                           'num_ini'=>'Numero inizio',
                           'num_fin'=>'Numero fine',
                           'period'=>'Imposta prossime scadenze',
                           'period_value'=>'Scadenze prossime',
                           'reprint'=>'Distintato',
                           'reprint_value'=>array('S'=>'Si','N'=>'No'),
                           'tot'=>'Totali del contenuto del file',
                           'eof'=>'Tracciato con caratteri di fine rigo',
                           'eof_title'=>'Ad ogni record verranno aggiunti i caratteri di fine rigo chr 13 e 10'
                           ),
                    "select_filemav.php" =>
                    array( 'title'=>'Generazione File dei MAV in formato CBI',
                           'errors'=>array('Non ci sono effetti da distintare nell\'intervallo selezionato',
                                           'Data non corretta',
                                           'La data di inizio &egrave; successiva a quella finale',
                                           'La data di emissione &egrave; successiva a quella iniziale'
                                          ),
                           'preview'=>'Anteprima del contenuto del file MAV in formato CBI',
                           'header'=>array('Num'=>'','Tipo'=>'','Scadenza'=>'','Importo'=>'',
                                            'Cliente/P.I.' =>'','Fattura/Importo'=>'','Appoggio/ABI-CAB'=>''
                                           ),
                           'date_emi'=>'Data della distinta',
                           'bank'=>'Banca d\'accredito',
                           'date_ini'=>'Data di scadenza inizio',
                           'date_fin'=>'Data di scadenza fine',
                           'num_ini'=>'Numero inizio',
                           'num_fin'=>'Numero fine',
                           'period'=>'Imposta prossime scadenze',
                           'period_value'=>'Scadenze prossime',
                           'reprint'=>'Distintato',
                           'reprint_value'=>array('S'=>'Si','N'=>'No'),
                           'tot'=>'Totali del contenuto del file'
                           ),
                    "error_msg.php" =>
                    array( 'admin_scontr'=>array(0=>'ATTENZIONE! <BR />Lei non risulta abilitato all\'invio di dati sul registratore di cassa (ECR), contattare l\'amministratore per modificare le impostazioni sulla tabella gaz_cash_register.')
                          ),
                    "accounting_documents.php" =>
                    array( 'title'=>'Genera i movimenti contabili a partire dai documenti fiscali',
                           'errors'=>array('Data non corretta',
                                           'Non ci sono documenti da contabilizzare nell\'intervallo selezionato'
                                          ),
                           'vat_section'=>' della sezione IVA n.',
                           'date'=>'Fino al :',
                           'type'=>'Registro IVA ',
                           'type_value'=>array('F'=>'delle Fatture di Vendita','V'=>'dei Corrispettivi'),
                           'proini'=>'Protocollo iniziale',
                           'profin'=>'Protocollo finale',
                           'preview'=>'Anteprima di contablizzazione',
                           'date_reg'=>'Data',
                           'protoc'=>'Protocollo',
                           'doc_type'=>'Tipo',
                           'doc_type_value'=>array('FAD'=>'FATTURA DIFFERITA A CLIENTE',
                                                   'FAI'=>'FATTURA IMMEDIATA A CLIENTE',
                                                   'FAP'=>'PARCELLA',
                                                   'FNC'=>'NOTA CREDITO A CLIENTE',
                                                   'FND'=>'NOTA DEBITO A CLIENTE',
                                                   'VCO'=>'CORRISPETTIVO',
                                                   'VRI'=>'RICEVUTA',
                                                   'AFA'=>'FATTURA D\'ACQUISTO',
                                                   'AFC'=>'NOTA CREDITO DA FORNITORE',
                                                   'AFD'=>'NOTA DEBITO DA FORNITORE'
                                                   ),
                           'customer'=>'Cliente/Fornitore',
                           'taxable'=>'Imponibile',
                           'vat'=>'I.V.A.',
                           'stamp'=>'Bolli su tratte',
                           'tot'=>'Totale'
                           ),
                    "import_gaziecart.php" =>
                    array( 'title'=>'Importazione ordini web provenienti da GAzieCart',
                           'errors'=>array('Non ci sono ordini da importare dalla casella e-mail'
                                          ),
                           'email'=>'Indirizzo usato per ricevere gli ordini: ',
                           'pass'=>'Password utilizzata per l\'accesso: ',
                           'server'=>'Indirizzo del server: ',
                           'name'=>'Ordine WEB',
                           'amount'=>'Totale imponibile',
                           'tot'=>'TOTALE ',
                           'tax'=>'I.V.A.',
                           'des1'=>' sul sito web: ',
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente/fornitore'),
                           'errors'=>array('Selezionare il cliente!',
                                           'Selezionare il tipo di pagamento',
                                           'Abilitare l\'estensione php_imap su php.ini per importare gli ordini'
                                          ),
                           ),
                    "select_effett.php" =>
                    array( 0=>'Stampa effetti',
                           'title'=>'Selezione per la visualizzazzione e/o la stampa degli effetti',
                           'ins_this'=>'Emetti un effetto a:',
                           'upd_this'=>'Modifica l\'effetto di ',
                           'del_this'=>'Elimina l\'effetto',
                           'sourcedoc'=>'Documento che ha originato l\'effetto',
                           'source'=>'Origine',
                           'link_1'=>'Genera effetti da fatture',
                           'link_2'=>'Emetti un nuovo effetto',
                           'link_3'=>'Contabilizzazione effetti',
                           'link_4'=>'Stampa effetti generati',
                           'link_5'=>'Distinta per banca',
                           'link_6'=>'Genera file Ri.Ba.',
                           'link_7'=>'Genera file MAV',
                           'report'=>'Lista degli effetti',
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente'),
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'La data di inizio degli effetti da stampare non pu&ograve; essere successiva alla data finale!',
                                           'Il numero iniziale non pu&ograve; essere successivo a quello finale!',
                                           'La data di emissione non pu&ograve; essere precedente a quella del documento di riferimento!',
                                           'La data di scadenza non pu&ograve; essere precedente a quella di emissione',
                                           'Numero di effetto minore di 1',
                                           'Si deve selezionare un cliente',
                                           'Importo effetto non valido',
                                           'Selezionare una banca d\'appoggio',
                                           'Selezionare il tipo di pagamento'
                                          ),
                           'progre'=>'Numero',
                           'type'=>'Tipo',
                           'type_pay'=>array('B'=>'Ri.Ba.','T'=>'Tratta','V'=>'Mediante Avviso (MAV)'),
                           'clfoco'=>'Cliente',
                           'date_emi'=>'Data di Emissione',
                           'numfat'=>'Numero della Fattura',
                           'vat_section'=>'Sezione IVA',
                           'date_doc'=>'Data della Fattura',
                           'totfat'=>'Importo della Fattura',
                           'salacc'=>'Acconto / Saldo',
                           'salacc_value'=>array('C'=>'Acconto','S'=>'Saldo'),
                           'impeff'=>'Importo Effetto',
                           'status'=>'Stato',
                           'date_exp'=>'Data di Scadenza',
                           'account_id'=>'Registrazione contabile numero',
                           'pagame'=>'Modalit&agrave; di pagamento',
                           'banapp'=>'Banca d\'appoggio',
                           'banacc'=>'Banca d\'accredito',
                           'num_ini'=>'Numero effetto inizio ',
                           'date_ini'=>'Data scadenza inizio  ',
                           'num_fin'=>'Numero effetto fine ',
                           'date_fin'=>'Data scadenza fine ',
                           'type_value'=>array('B'=>'Ricevute Bancarie','T'=>'Tratte','V'=>'MAV'),
                           'header'=>array('Num'=>'','Scadenza'=>'','Importo'=>'',
                                            'Cliente' =>'','Fattura'=>'','Appoggio'=>''
                                           )
                           ),
                    "report_schedule.php" =>
                    array( 'title'=>'Lista dei movimenti delle partite',
                           'header'=>array( 'ID'=>'id',
                                            'Identificativo partita' => "id_tesdoc_ref",
                                            'Movimento contabile apertura (documento)' => "id_rigmoc_doc",
                                            'Movimento contabile chiusura (pagamento)' => "id_rigmoc_pay",
                                            'Importo' => "amount",
                                            'Scadenza' => "expiry"
                                            ),
                           ),
                    "select_schedule.php" =>
                    array( 'title'=>'Selezione per la visualizzazzione e/o la stampa delle partite aperte',
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente/fornitore'
                                          ),
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'Non sono stati trovati movimenti!'
                                          ),
                           'account'=>'Cliente ',
                           'orderby'=>'Ordina per: ',
                           'orderby_value'=>array(0=>'Scadenza crescente',1=>'Scadenza decrescente',
                                                  2=>'Cliente crescente',3=>'Cliente decrescente'
                                           ),
                           'header'=>array('Cliente'=>'','ID Partita'=>'','Status'=>'','Mov.Cont.'=>'','Descrizione'=>'',
                                            'N.Doc.'=>'','Data Doc.' =>'','Data Reg.' =>'','Dare'=>'','Avere'=>'',
                                            'Scadenza'=>''
                                           ),
                           'status_value'=>array(0=>'Chiusa',1=>'Aperta'),
                           ),
                    "delete_schedule.php" =>
                    array( 'title'=>'Cancellazione movimenti chiusi dello scadenzario',
                           'ragsoc'=>'Cliente',
                           'id_tesdoc_ref'=>'Identificativo partita',
                           'descri'=> 'Descrizione'
                           ),
                    "select_evaord.php" =>
                    array( 'title'=>'Evasione degli ordini del cliente',
                           'errors'=>array('Non &egrave; stato selezionato un cliente',
                                           'Non ci sono righi',
                                           'Non ci sono righi inevasi per generare il documento selezionato',
                                           'Non hai selezionato la modalit&agrave; di pagamento',
                                           'La data di emissione non &egrave; corretta',
                                           'La data di inizio trasporto non &egrave; corretta',
                                           'La data di inizio trasporto non pu&ograve; essere precedente alla data di emissione',
                                           'NON HAI ESEGUITO LA CHIUSURA GIORNALIERA DEL REGISTRATORE DI CASSA FALLO PRIMA DI EMETTERNE UNO!!!'
                                          ),
                           'customer'=>'Cliente',
                           'search_customer'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente',
                                         'Scegli un cliente',
                                         ' C.F.:',
                                         'Anonimo'
                                          ),
                           'indspe'=>'Indirizzo',
                           'seziva'=>'Sezione IVA',
                           'destin'=>'Destinazione',
                           'banapp'=> 'Banca',
                           'listin'=>'Listino n.',
                           'datemi'=>'Data ',
                           'initra'=>'Inizio trasporto ',
                           'traspo'=>'Trasporto ',
                           'spediz'=>'Spedizione ',
                           'portos'=>'Porto/Resa ',
                           'imball'=>'Imballo ',
                           'vettor'=>'Vettore ',
                           'sconto'=>'Sconto',
                           'pagame'=>'Pagamento',
                           'preview_title'=>'ORDINI DA EVADERE:',
                           'from'=>'da Ordine n.',
                           'del'=>' del ',
                           'upd_ord'=>' Modifica l\'ordine',
                           'id_agente'=>'Agente ',
                           'codart'=>'Codice',
                           'descri'=>'Descrizione',
                           'unimis'=>'U.M.',
                           'quanti'=>'Quantità ',
                           'prezzo'=>'Prezzo',
                           'provvigione'=>'%Prov',
                           'amount'=>'Importo',
                           'taxable'=>'Imponibile',
                           'issue_fat'=>'Evadi con Fattura Immediata',
                           'issue_ddt'=>'Evadi con Documento di Trasporto',
                           'issue_cor'=>'Evadi con Corrispettivo',
                           'checkbox'=>'Questa checkbox dev\'essere selezionata per evadere il rigo',
                           'alert1'=>'&sup1; La sezione IVA scelta non &egrave; quella<br/>normalente usata per<br/>l\'emissione delle Fatture immediate.',
                           'alert2'=>'&sup1; La sezione IVA selezionata potrebbe non<br/>coincidere con quella che verr&agrave; usata per<br/>l\'emissione della Fattura immediata che per<br/>Vostra scelta sar&agrave; uguale all\'ultima emessa.'
                           ),
                    "select_partner_status.php" =>
                    array( 'title'=>'Selezione per la visualizzazzione e/o la stampa dello scadenzario dei clienti',
                           'print_title'=>'SCADENZARIO CLIENTI ',
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'err'=>'Ci sono degli errori che impediscono la stampa'
                                          ),
                           'date_ini'=>'Data di riferimento ',
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>''
                                           ),
                            'status_value'=>array(0=>'APERTA',1=>'CHIUSA',2=>'ESPOSTA',3=>'SCADUTA',9=>'ANTICIPO')
                           ),
                    "customer_payment.php" =>
                    array( 'title'=>'Riscossione credito da cliente (chiusura partita/e)',
                           'errors'=>array('La data  non &egrave; corretta!',
                                           'err'=>'Ci sono degli errori che impediscono la stampa'
                                          ),
                           'partner'=>'Cliente ',
                           'date_ini'=>'Data di registrazione',
                           'target_account'=>"Conto per l'incasso: ",
                           'partner'=>'Cliente: ',
                           'print_ticket'=>"Stampa ricevuta: ",
                           'accbal'=>'Saldo risultante dai movimenti contabili: ',
                           'paymovbal'=>'Saldo risultante dalle partite aperte: ',
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>''
                                           ),
                           'status_value'=>array(0=>'APERTA',1=>'CHIUSA',2=>'ESPOSTA',3=>'SCADUTA',9=>'ANTICIPO'),
                           'header'=>array('ID'=>'','Importo apertura'=>'','Data Scadenza'=>'','Importo chiusura'=>''
                                           ,'Data chiusura'=>'','Giorni esposizione' =>'','Stato'=>'', 'Riscuoti'=>''
                                           ),
                           'mesg'=>array('La ricerca non ha dato risultati!',
                                         'Inserire almeno 2 caratteri!',
                                         'Cambia cliente',
                                         'Il saldo contabile è diverso da quello dello scadenzario,<br> se vuoi registrare la riscossione di un documento presente solo in contabilità  fallo da qui:',
                                         'Nessun importo è stato riscosso!',
					 "Non è stato selezionato il conto per l'incasso",
                                         'Stai tentando di inserire il pagamento di un cliente senza movimenti'
                                          ),
                           ),
                    "print_customer_payment_receipt.php" =>
                    array( 'title'=>'RISCOSSIONE CREDITO DA ',
                           'id_tesdoc_ref'=>'ID Partita',
                           'descri'=>'Descrizione',
                           'numfat'=>'Numero fattura',
                           'datfat'=>'Data fattura',
                           'amount'=>'Importo riscosso',
                           'tot'=>'TOTALE DELLA RISCOSSIONE',
                           ),
                   "report_fae_sdi.php" =>
                   array(  'title'=>'TRAFFICO DATI FATTURAZIONE ELETTRONICA',
                           'table'=>'Tabella su cui stai lavorando: ',
                           'id'=>'ID',
                           'filename_ori'=>'Nome file primo invio',
                           'numfat'=>'N.<br>fattura',
                           'codice'=>'Cod. cliente',
                           'ragso1'=>'Amministrazione',
                           'exec_date'=>'Data di esecuzione ',
                           'received_date'=>'Data ricezione ',
                           'delivery_date'=>'Data consegna ',
                           'filename_son'=>'Nome file padre',
                           'id_SDI'=>'ID SDI',
                           'filename_ret'=>'Nome file di ritorno',
                           'mail_id'=>'UID della mail',
                           'flux_status'=>'Stato',
                           'flux_status_value'=>array(''=>'Generato',
						                              '#'=>'Non ancora inviata',
                                                      '@'=>'Inviata',
                                                      'NS'=>'Notifica scarto',
                                                      'MC'=>'Mancata Consegna',
                                                      'RC'=>'Ricevuta consegna',
                                                      'NE'=>'Notifica esito',
                                                      'DT'=>'Decorrenza termini'),
                           'progr_ret'=>'Progr.',
                           'flux_descri'=>'Descrizione'
                         )                           
                   );
?>