UPDATE `gaz_config` SET `cvalue` = '90' WHERE `id` =2;
INSERT INTO `gaz_menu_module` SELECT MAX(id)+1, '8', 'ruburl.php', '', '', '6', '', '6'  FROM `gaz_menu_module`;
INSERT INTO `gaz_menu_script` SELECT MAX(id)+1, (SELECT MAX(id) FROM `gaz_menu_module`), 'report_ruburl.php', '', '', '4', '', '1'  FROM `gaz_menu_script`;
INSERT INTO `gaz_menu_script` SELECT MAX(id)+1, (SELECT MAX(id) FROM `gaz_menu_module`), 'admin_ruburl.php?Insert', '', '', '5', '', '2'  FROM `gaz_menu_script`;
UPDATE `gaz_menu_module` SET `link` = 'docume_inform.php' WHERE `link` = 'gaziecart_update.php';
INSERT INTO `gaz_menu_script` SELECT MAX(id)+1, (SELECT id FROM `gaz_menu_module` WHERE `link` = 'docume_inform.php' LIMIT 1), 'gaziecart_update.php', '', '', '6', '', '1'  FROM `gaz_menu_script`;
INSERT INTO `gaz_menu_script` SELECT MAX(id)+1, (SELECT id FROM `gaz_menu_module` WHERE `link` = 'docume_inform.php' LIMIT 1), 'gazie_site_update.php', '', '', '7', '', '2'  FROM `gaz_menu_script`;
-- START_WHILE ( questo e' un tag che serve per istruire install.php ad INIZIARE ad eseguire le query seguenti su tutte le aziende dell'installazione)
INSERT INTO `gaz_XXXcompany_config` (`description`, `var`, `val`) VALUES ( 'Gazie - Gestionale', 'ruburl', 'http://gazie.sourceforge.net/');
INSERT INTO `gaz_XXXcompany_data` (`id`, `description`, `var`, `data`, `ref`) VALUES
(1, '', 'website_title', '- website generator', ''),
(2, '', 'website_subtitle', 'erp free and open source', ''),
(3, '', 'website_meta_author', 'Antonio de Vincentiis - http://devincentiis.it', ''),
(4, '', 'website_meta_keywords', 'software libero open source erp crm magazzino gestionale contabilità iva registi magazzino azienda partitario scadenzario saldo acconto fattura ddt bolla parcella cliente fornitore sollecito scarico carico bilancio cee consolidato utile perdita registro libro', ''),
(5, 'Azienda', 'website_page_index', '<p>Il contenuto di questa pagina iniziale la potrai modificare a piacimento prima della pubblicazione descrivendo l''attività svolta dalla tua azienda.</p><p>\r\nGazie o GAzie - Gestione Aziendale è un programma gestionale multiaziendale eseguibile su web server Apache con il supporto per il PHP e database MySQL. Con esso è possibile emettere ogni tipo di documento di vendita (DdT, Fatture Immediate, Fatture Differite, Note di Credito e Debito, Parcelle, Contratti, ecc.) ed eventualmente i relativi effetti (Ri.Ba elettroniche/cartacee, Cambiali-tratte) per il loro pagamento</p><p>\r\nGAzie emette tutti i libri obbligatori per la contabilità semplificata, ordinaria e di magazzino di una piccola/media azienda. Ogni operazione di stampa cartacea genera comunque il documento in formato PDF che in automatico può essere spedito via mail ai destinatari.</p>\r\n<br/>\r\n<p class="gazie_other">Orari nei quali è probabile che stiamo lavorando con GAzie:</p>\r\n<p>Dal lunedì al venerdì dalle 8:00 alle 12:15 e dalle 14:30 alle 17:45 </p>', ''),
(6, 'Prodotti', 'website_page_product', '<p>Di seguito sono elencati i nostri prodotti </p>', ''),
(7, 'Contatti', 'website_page_contact', '	<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">\r\n	<tbody>\r\n		<tr>\r\n			<td height="20" class="gazie_other">Nome</td>\r\n			<td height="20" class="gazie_other">Ruolo</td>\r\n			<td height="20" class="gazie_other">Telefono</td>\r\n			<td height="20" class="gazie_other">Cellulare</td>\r\n			<td height="20" class="gazie_other">Fax</td>\r\n			<td height="20" class="gazie_other">E-mail</td>\r\n		</tr>\r\n		<tr>\r\n			<td height="20">Amministrazione</td>\r\n			<td>Informazioni</td>\r\n			<td>085 42 21 477</td>\r\n			<td></td>\r\n			<td>085 42 21 477</td>\r\n			<td>gazie-list@lists.sourceforge.net</td>\r\n		</tr>\r\n		<tr>\r\n			<td height="20">Antonio</td>\r\n			<td>Vendite, acquisti, contabilità</td>\r\n			<td></td>\r\n			<td>338 31 21 161</td>\r\n			<td></td>\r\n			<td>a.devincentiis@tiscali.it</td>\r\n		</tr>\r\n		<tr>\r\n			<td height="20">Fax</td>\r\n			<td>Vendite, acquisti, magazzino</td>\r\n			<td></td>\r\n			<td>085 42 21 477</td>\r\n			<td></td>\r\n			<td></td>\r\n		</tr>\r\n	</tbody>\r\n	</table>\r\n', ''),
(8, 'Dove siamo', 'website_page_where', '		<p> Via Volturno 2 - 65016 MONTESILVANO PESCARA (PE)\r\n		<p><iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.openstreetmap.org/export/embed.html?bbox=14.163796305656433%2C42.505353124694636%2C14.166789650917053%2C42.50649207518226&amp;layer=mapnik&amp;marker=42.50592260253225%2C14.165292978286743" style="border: 1px solid black"></iframe><br/><small><a href="http://www.openstreetmap.org/?mlat=42.50592&amp;mlon=14.16529#map=19/42.50592/14.16529">Visualizza mappa ingrandita</a></small></p>', '');
-- STOP_WHILE ( questo e' un tag che serve per istruire install.php a SMETTERE di eseguire le query su tutte le aziende dell'installazione)